In [1]:
import requests as r
from bs4 import BeautifulSoup as BS
import pandas as pd
import re
import time as t
import os
import TheOutnetWS as WS

In [2]:
os.getcwd()

'C:\\Users\\mathi\\Documents\\GitHub\\data-labs\\module-1\\lab-web-scraping'

In [3]:
colnames=['Brand','Description','SalePrice','OriginalPrice']

In [4]:
Brand,Description,SalePrice,OriginalPrice=WS.web_scraper('https://www.theoutnet.com/Search/RenderProductsAsync?ytosQuery=true&linkdepartment=INTL_Dresses_CLOTHING&linkdepartmentId=3074457345616677807&department=INTL_Dresses_CLOTHING&departmentId=3074457345616677807&page=%i&productsPerPage=96&suggestion=false&facetsvalue=&totalPages=75&rsiUsed=false&totalItems=7192&partialLoadedItems=96&itemsToLoadOnNextPage=96&siteCode=THEOUTNET_FR&langId=19',78)

C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\TheOutnetWS.py:19: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 19 of the file C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\TheOutnetWS.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  lst=BS(r.get(url).content).select('div.description>span.designer-name,span.discounted>span.value,span.full>span.value,div.description>span.title')

In [5]:
df_dress=pd.DataFrame([Brand,Description,SalePrice,OriginalPrice],index=colnames).T
df_dress

,Brand,Description,SalePrice,OriginalPrice
0,IRIS & INK,Siri wrap-effect satin-crepe dress,145,
1,IRIS & INK,Marne pleated crepe dress,155,
2,IRIS & INK,Elina gathered crepe dress,130,
3,CAMILLA,Crystal-embellished knotted silk crepe de chin...,387,745
4,TORY BURCH,Ruffled striped broderie anglaise cotton midi ...,280,585
5,RACHEL ZOE,Asymmetric floral-print silk-georgette dress,172,400
6,APIECE APART,Meru asymmetric printed silk crepe de chine wr...,312,600
7,TEMPERLEY LONDON,Beaux broderie anglaise-trimmed ruffled Swiss-...,312,695
8,GÜL HÜRGEL,Belted gingham cotton and linen-blend maxi shi...,360,720
9,APIECE APART,Asymmetric off-the-shoulder floral-print cotto...,235,490
10,BORGO DE NOR,Gathered floral-print fil coupé maxi dress,355,725
11,APIECE APART,Lypie ruffle-trimmed striped cotton-gauze maxi...,202,440
12,DKNY,Cady sheath dress,90,165
13,GÜL HÜRGEL,Gathered floral-print cotton midi dress,442,885
14,MIKAEL AGHAL,Ruffled floral-print georgette dress,344,765
15,McQ Alexander McQueen,Embroidered jersey mini dress,156,285
16,NICHOLAS,Floral-print silk crepe de chine mini dress,255,510
17,RACHEL ZOE,Susanna bow-detailed ruffled organza gown,270,540
18,McQ Alexander McQueen,Paneled printed cotton-jersey mini dress,111,185
19,PACO RABANNE,Lace-trimmed satin maxi dress,345,690
20,MIKAEL AGHAL,Tie-neck stretch-crepe dress,369,820
21,ALICE + OLIVIA,Floral-jacquard mini dress,208,416
22,NICHOLAS,Ruffled floral-print silk-georgette mini dress,319,615
23,DIANE VON FURSTENBERG,Crepe-satin gown,324,590
24,McQ Alexander McQueen,Cotton-jersey mini dress,71,130
25,NICHOLAS,Belted ruched cotton and silk-blend mini dress,247,475
26,ZIMMERMANN,Unbridled Elixir cold-shoulder cutout floral-p...,865,1730
27,MIKAEL AGHAL,Ruffle-trimmed printed chiffon maxi dress,443,985
28,MIKAEL AGHAL,Draped crepe dress,348,775
29,CEFINN,Belted gauze mini dress,178,320
...,...,...,...,...
7189,VALENTINO,Scalloped metallic embroidered tulle midi dress,1308,6535
7190,LOVE SAM,Lace-trimmed voile mini dress,58,238
7191,ZIMMERMANN,Cold-shoulder ruffled silk-satin mini dress,328,655
7192,FILIPPA K,Stretch-jersey dress,58,190
7193,MARNI,Paneled checked cotton-blend midi dress,344,860
7194,MARNI,Embellished printed silk crepe dmaxi dress,529,1765
7195,NICHOLAS,Cold-shoulder ruffle-trimmed cotton-poplin min...,74,370
7196,IRO,Blank asymmetric layered printed gauze dress,225,450
7197,STELLA McCARTNEY,Tulle-paneled stretch-jersey dress,433,866
7198,W118 by WALTER BAKER,Tamisha metallic ruffled jacquard chiffon mini...,70,285
7199,KHAITE,Carolina satin-crepe midi slip dress,398,1325
7200,PAPER London,Bow-detailed linen halterneck maxi dress,252,525
7201,BY MALENE BIRGER,Quinnas tie-front crepe-jersey dress,49,205
7202,W118 by WALTER BAKER,Fiona ruffled floral-print crepe de chine dress,68,270
7203,TART COLLECTIONS,Raffaella printed crepe de chine mini dress,50,167
7204,DEITAS,One-shoulder silk midi dress,268,535
7205,CAROLINE CONSTAS,Gisele off-the-shoulder printed cotton-poplin ...,232,485
7206,RACHEL ZOE,Brighton fringed draped satin midi dress,68,440
7207,REJINA PYO,Paneled satin midi dress,298,1005
7208,GOAT,Alexa wool-crepe dress,208,413
7209,GANNI,Mercer fluted merino wool-blend mini dress,49,199
7210,LOVE STORIES,Cato metallic cotton-blend slip dress,34,110
7211,ENZA COSTA,Ruched stretch-jersey mini dress,40,180
7212,ALICE McCALL,Move With Me ruffle-trimmed ruched taffeta dress,60,400
7213,BAUM UND PFERDGARTEN,Aamina mesh-paneled ruffled jacquard dress,52,210
7214,HALSTON HERITAGE,Georgette-paneled crepe gown,202,450
7215,BY MALENE BIRGER,Quinnas tie-front printed jersey dress,48,230
7216,BY MALENE BIRGER,Majao tie-front crepe-jersey maxi dress,42,285
7217,ANTIK BATIK,Lace-trimmed cotton-gauze midi dress,152,305
7218,BY MALENE BIRGER,Willos wrap-effect stretch-crepe dress,42,210

In [6]:
df_dress=df_dress.drop_duplicates()
df_dress

,Brand,Description,SalePrice,OriginalPrice
0,IRIS & INK,Siri wrap-effect satin-crepe dress,145,
1,IRIS & INK,Marne pleated crepe dress,155,
2,IRIS & INK,Elina gathered crepe dress,130,
3,CAMILLA,Crystal-embellished knotted silk crepe de chin...,387,745
4,TORY BURCH,Ruffled striped broderie anglaise cotton midi ...,280,585
5,RACHEL ZOE,Asymmetric floral-print silk-georgette dress,172,400
6,APIECE APART,Meru asymmetric printed silk crepe de chine wr...,312,600
7,TEMPERLEY LONDON,Beaux broderie anglaise-trimmed ruffled Swiss-...,312,695
8,GÜL HÜRGEL,Belted gingham cotton and linen-blend maxi shi...,360,720
9,APIECE APART,Asymmetric off-the-shoulder floral-print cotto...,235,490
10,BORGO DE NOR,Gathered floral-print fil coupé maxi dress,355,725
11,APIECE APART,Lypie ruffle-trimmed striped cotton-gauze maxi...,202,440
12,DKNY,Cady sheath dress,90,165
13,GÜL HÜRGEL,Gathered floral-print cotton midi dress,442,885
14,MIKAEL AGHAL,Ruffled floral-print georgette dress,344,765
15,McQ Alexander McQueen,Embroidered jersey mini dress,156,285
16,NICHOLAS,Floral-print silk crepe de chine mini dress,255,510
17,RACHEL ZOE,Susanna bow-detailed ruffled organza gown,270,540
18,McQ Alexander McQueen,Paneled printed cotton-jersey mini dress,111,185
19,PACO RABANNE,Lace-trimmed satin maxi dress,345,690
20,MIKAEL AGHAL,Tie-neck stretch-crepe dress,369,820
21,ALICE + OLIVIA,Floral-jacquard mini dress,208,416
22,NICHOLAS,Ruffled floral-print silk-georgette mini dress,319,615
23,DIANE VON FURSTENBERG,Crepe-satin gown,324,590
24,McQ Alexander McQueen,Cotton-jersey mini dress,71,130
25,NICHOLAS,Belted ruched cotton and silk-blend mini dress,247,475
26,ZIMMERMANN,Unbridled Elixir cold-shoulder cutout floral-p...,865,1730
27,MIKAEL AGHAL,Ruffle-trimmed printed chiffon maxi dress,443,985
28,MIKAEL AGHAL,Draped crepe dress,348,775
29,CEFINN,Belted gauze mini dress,178,320
...,...,...,...,...
7186,DIANE VON FURSTENBERG,Bow-detailed printed silk midi dress,391,783
7187,ROSIE ASSOULIN,Booby Trap off-the-shoulder tie-front cotton-b...,421,1240
7188,JOSEPH,Fay ruched printed devoré silk-blend chiffon m...,524,1220
7189,VALENTINO,Scalloped metallic embroidered tulle midi dress,1308,6535
7190,LOVE SAM,Lace-trimmed voile mini dress,58,238
7191,ZIMMERMANN,Cold-shoulder ruffled silk-satin mini dress,328,655
7193,MARNI,Paneled checked cotton-blend midi dress,344,860
7194,MARNI,Embellished printed silk crepe dmaxi dress,529,1765
7195,NICHOLAS,Cold-shoulder ruffle-trimmed cotton-poplin min...,74,370
7197,STELLA McCARTNEY,Tulle-paneled stretch-jersey dress,433,866
7198,W118 by WALTER BAKER,Tamisha metallic ruffled jacquard chiffon mini...,70,285
7199,KHAITE,Carolina satin-crepe midi slip dress,398,1325
7200,PAPER London,Bow-detailed linen halterneck maxi dress,252,525
7201,BY MALENE BIRGER,Quinnas tie-front crepe-jersey dress,49,205
7202,W118 by WALTER BAKER,Fiona ruffled floral-print crepe de chine dress,68,270
7203,TART COLLECTIONS,Raffaella printed crepe de chine mini dress,50,167
7204,DEITAS,One-shoulder silk midi dress,268,535
7205,CAROLINE CONSTAS,Gisele off-the-shoulder printed cotton-poplin ...,232,485
7206,RACHEL ZOE,Brighton fringed draped satin midi dress,68,440
7207,REJINA PYO,Paneled satin midi dress,298,1005
7208,GOAT,Alexa wool-crepe dress,208,413
7209,GANNI,Mercer fluted merino wool-blend mini dress,49,199
7210,LOVE STORIES,Cato metallic cotton-blend slip dress,34,110
7211,ENZA COSTA,Ruched stretch-jersey mini dress,40,180
7213,BAUM UND PFERDGARTEN,Aamina mesh-paneled ruffled jacquard dress,52,210
7214,HALSTON HERITAGE,Georgette-paneled crepe gown,202,450
7215,BY MALENE BIRGER,Quinnas tie-front printed jersey dress,48,230
7216,BY MALENE BIRGER,Majao tie-front crepe-jersey maxi dress,42,285
7217,ANTIK BATIK,Lace-trimmed cotton-gauze midi dress,152,305
7218,BY MALENE BIRGER,Willos wrap-effect stretch-crepe dress,42,210

In [7]:
df_dress.Description='Dress'
df_dress

C:\Users\mathi\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

                      Brand Description SalePrice OriginalPrice
0                IRIS & INK       Dress       145
1                IRIS & INK       Dress       155
2                IRIS & INK       Dress       130
3                   CAMILLA       Dress       387           745
4                TORY BURCH       Dress       280           585
5                RACHEL ZOE       Dress       172           400
6              APIECE APART       Dress       312           600
7          TEMPERLEY LONDON       Dress       312           695
8                GÜL HÜRGEL       Dress       360           720
9              APIECE APART       Dress       235           490
10             BORGO DE NOR       Dress       355           725
11             APIECE APART       Dress       202           440
12                     DKNY       Dress        90           165
13               GÜL HÜRGEL       Dress       442           885
14             MIKAEL AGHAL       Dress       344           765
15    McQ Alexander McQueen       Dress       156           285
16                 NICHOLAS       Dress       255           510
17               RACHEL ZOE       Dress       270           540
18    McQ Alexander McQueen       Dress       111           185
19             PACO RABANNE       Dress       345           690
20             MIKAEL AGHAL       Dress       369           820
21           ALICE + OLIVIA       Dress       208           416
22                 NICHOLAS       Dress       319           615
23    DIANE VON FURSTENBERG       Dress       324           590
24    McQ Alexander McQueen       Dress        71           130
25                 NICHOLAS       Dress       247           475
26               ZIMMERMANN       Dress       865          1730
27             MIKAEL AGHAL       Dress       443           985
28             MIKAEL AGHAL       Dress       348           775
29                   CEFINN       Dress       178           320
...                     ...         ...       ...           ...
7186  DIANE VON FURSTENBERG       Dress       391           783
7187         ROSIE ASSOULIN       Dress       421          1240
7188                 JOSEPH       Dress       524          1220
7189              VALENTINO       Dress      1308          6535
7190               LOVE SAM       Dress        58           238
7191             ZIMMERMANN       Dress       328           655
7193                  MARNI       Dress       344           860
7194                  MARNI       Dress       529          1765
7195               NICHOLAS       Dress        74           370
7197       STELLA McCARTNEY       Dress       433           866
7198   W118 by WALTER BAKER       Dress        70           285
7199                 KHAITE       Dress       398          1325
7200           PAPER London       Dress       252           525
7201       BY MALENE BIRGER       Dress        49           205
7202   W118 by WALTER BAKER       Dress        68           270
7203       TART COLLECTIONS       Dress        50           167
7204                 DEITAS       Dress       268           535
7205       CAROLINE CONSTAS       Dress       232           485
7206             RACHEL ZOE       Dress        68           440
7207             REJINA PYO       Dress       298          1005
7208                   GOAT       Dress       208           413
7209                  GANNI       Dress        49           199
7210           LOVE STORIES       Dress        34           110
7211             ENZA COSTA       Dress        40           180
7213   BAUM UND PFERDGARTEN       Dress        52           210
7214       HALSTON HERITAGE       Dress       202           450
7215       BY MALENE BIRGER       Dress        48           230
7216       BY MALENE BIRGER       Dress        42           285
7217            ANTIK BATIK       Dress       152           305
7218       BY MALENE BIRGER       Dress        42           210

[6808 rows x 4 columns]

In [8]:
Brand1,Description1,SalePrice1,OriginalPrice1=WS.web_scraper('https://www.theoutnet.com/Search/RenderProductsAsync?ytosQuery=true&linkdepartment=INTL_Jackets_CLOTHING&linkdepartmentId=3074457345616677808&department=INTL_Jackets_CLOTHING&departmentId=3074457345616677808&gender=&brand=&macro=&micro=&season=&color=&size=&site=&section=&sortRule=&yurirulename=&microcolor=&agerange=&macroMarchio=&page=%i&productsPerPage=96&modelnames=&look=&washtype=&fabric=&prints=&suggestion=false&suggestionValue=&material=&occasion=&weight=&gallery=&colortype=&style=&issale=&heeltype=&wedge=&salesline=&family=&environment=&structure=&authorlocalized=&themecollection=&waist=&stone=&filter=&collection=&price=&facetsvalue=&model=&virtualnavigation=&textSearchFilters=&textSearch=&minMaxPrice=&searchType=&fabricColor=&modelFabric=&itembinding=&totalPages=20&rsiUsed=false&totalItems=1866&partialLoadedItems=96&itemsToLoadOnNextPage=96&siteCode=THEOUTNET_FR&langId=19',20)

In [9]:
df_jacket=pd.DataFrame([Brand1,Description1,SalePrice1,OriginalPrice1],index=colnames).T
df_jacket

,Brand,Description,SalePrice,OriginalPrice
0,JOHANNA ORTIZ,Fringed polka-dot satin-jacquard jacket,659,1465
1,PACO RABANNE,Cropped metallic-trimmed denim jacket,245,490
2,APIECE APART,Boro color-block quilted cotton and silk-blend...,232,540
3,RACHEL ZOE,Belted floral-print crepe blazer,189,378
4,DKNY,Jacquard jacket,90,165
5,ALICE + OLIVIA,Jace oversized embellished satin blazer,385,770
6,RACIL,Archie double-breasted wool-crepe blazer,376,785
7,DIANE VON FURSTENBERG,Cali cady wrap blazer,322,645
8,EMILIO PUCCI,Crystal-embellished silk crepe de chine cape,564,1375
9,RE/DONE,Cropped cotton-ripstop jacket,430,
10,ALICE + OLIVIA,Ester reversible knitted coat,269,538
11,TEMPERLEY LONDON,Millais printed silk-chiffon cape,697,1395
12,PACO RABANNE,Printed shell hooded jacket,145,290
13,ZIMMERMANN,Fleeting leather-trimmed shearling jacket,1350,2700
14,ALICE + OLIVIA,Floral-jacquard blazer,285,549
15,SONIA RYKIEL,Double-breasted striped ponte jacket,571,1190
16,BAUM UND PFERDGARTEN,Bian gingham twill jacket,177,354
17,PACO RABANNE,Oversized printed cotton-jersey hoodie,145,290
18,RACIL,Audrey double-breasted satin-trimmed checked w...,404,880
19,MARKUS LUPFER,Maddy embroidered stretch-jersey track jacket,138,300
20,RACIL,Archie double-breasted wool-crepe blazer,376,785
21,ZIMMERMANN,Printed wool-blend twill blazer,584,1460
22,TORY BURCH,Suede bomber jacket,417,995
23,ZIMMERMANN,Belted denim jacket,310,690
24,RACIL,Grace belted velvet robe,396,825
25,LANVIN,Silk satin-trimmed wool blazer,1116,2790
26,GIAMBATTISTA VALLI,Embellished bouclé-tweed jacket,959,2133
27,REDValentino,Jacquard jacket,514,1050
28,KARL DONOGHUE,Shearling vest,585,
29,R13,Embroidered shell bomber jacket,312,625
...,...,...,...,...
1803,REBECCA MINKOFF,Double-breasted Prince of Wales checked woven ...,246,535
1804,IRO,Agnette distressed cotton bouclé-tweed jacket,208,425
1805,KHAITE,Woven blazer,589,1310
1806,DIANE VON FURSTENBERG,Linen-blend twill jacket,279,621
1807,LINE,Printed cotton-blend jacket,78,155
1808,MICHAEL MICHAEL KORS,Embellished crepe jacket,175,350
1809,DEREK LAM 10 CROSBY,Flocked cotton-blend twill blazer,160,535
1810,DEREK LAM 10 CROSBY,Metallic shell hooded jacket,154,510
1811,MICHAEL MICHAEL KORS,Double-breasted wool-blend blazer,175,350
1812,VANESSA BRUNO,Itaz crepe blazer,118,395
1813,MICHAEL MICHAEL KORS,Studded crepe jacket,187,375
1814,VAKKO by PIAZZA SEMPIONE,Crepe blazer,175,875
1815,RE/DONE with LEVI'S,French cotton-terry hooded jacket,107,179
1816,BAUM UND PFERDGARTEN,Ruffle-trimmed floral-print silk-blend twill b...,54,270
1817,IRO,Quilombe metallic houndstooth tweed jacket,120,400
1818,SONIA RYKIEL,Cotton-poplin trench coat,195,650
1819,KAIN,Crepe jacket,104,190
1820,L'AGENCE,Zuma lace-up cropped denim jacket,98,336
1821,TIBI,Steward double-breasted woven blazer,198,670
1822,ALICE + OLIVIA,Cropped printed French cotton-terry hooded swe...,90,306
1823,BY MALENE BIRGER,Vinue tie-front twill jacket,118,490
1824,DKNY,Scuba bomber jacket,81,151
1825,SPLENDID,Coated French cotton-terry biker jacket,80,320
1826,OPENING CEREMONY,Leather-paneled appliquéd corduroy jacket,145,485
1827,RAG & BONE,Denim jacket,64,320
1828,REBECCA TAYLOR,Double-breasted slub linen-blend blazer,222,445
1829,CINQ À SEPT,Lennox cropped feather-embellished mesh jacket,215,1075
1830,SANDRO,Soazic double-breasted cotton-blend blazer,171,285
1831,MSGM,Cropped cotton-blend tweed jacket,158,785
1832,TIBI,Lace-up marled cotton-blend twill blazer,128,845

In [10]:
df_jacket=df_jacket.drop_duplicates()
df_jacket.Description='Jacket'
df_jacket

                         Brand Description SalePrice OriginalPrice
0                JOHANNA ORTIZ      Jacket       659          1465
1                 PACO RABANNE      Jacket       245           490
2                 APIECE APART      Jacket       232           540
3                   RACHEL ZOE      Jacket       189           378
4                         DKNY      Jacket        90           165
5               ALICE + OLIVIA      Jacket       385           770
6                        RACIL      Jacket       376           785
7        DIANE VON FURSTENBERG      Jacket       322           645
8                 EMILIO PUCCI      Jacket       564          1375
9                      RE/DONE      Jacket       430
10              ALICE + OLIVIA      Jacket       269           538
11            TEMPERLEY LONDON      Jacket       697          1395
12                PACO RABANNE      Jacket       145           290
13                  ZIMMERMANN      Jacket      1350          2700
14              ALICE + OLIVIA      Jacket       285           549
15                SONIA RYKIEL      Jacket       571          1190
16        BAUM UND PFERDGARTEN      Jacket       177           354
17                PACO RABANNE      Jacket       145           290
18                       RACIL      Jacket       404           880
19               MARKUS LUPFER      Jacket       138           300
21                  ZIMMERMANN      Jacket       584          1460
22                  TORY BURCH      Jacket       417           995
23                  ZIMMERMANN      Jacket       310           690
24                       RACIL      Jacket       396           825
25                      LANVIN      Jacket      1116          2790
26          GIAMBATTISTA VALLI      Jacket       959          2133
27                REDValentino      Jacket       514          1050
28               KARL DONOGHUE      Jacket       585
29                         R13      Jacket       312           625
30               KARL DONOGHUE      Jacket       709          1290
...                        ...         ...       ...           ...
1803           REBECCA MINKOFF      Jacket       246           535
1804                       IRO      Jacket       208           425
1805                    KHAITE      Jacket       589          1310
1806     DIANE VON FURSTENBERG      Jacket       279           621
1807                      LINE      Jacket        78           155
1808      MICHAEL MICHAEL KORS      Jacket       175           350
1809       DEREK LAM 10 CROSBY      Jacket       160           535
1810       DEREK LAM 10 CROSBY      Jacket       154           510
1811      MICHAEL MICHAEL KORS      Jacket       175           350
1812             VANESSA BRUNO      Jacket       118           395
1813      MICHAEL MICHAEL KORS      Jacket       187           375
1814  VAKKO by PIAZZA SEMPIONE      Jacket       175           875
1815       RE/DONE with LEVI'S      Jacket       107           179
1816      BAUM UND PFERDGARTEN      Jacket        54           270
1817                       IRO      Jacket       120           400
1818              SONIA RYKIEL      Jacket       195           650
1819                      KAIN      Jacket       104           190
1820                  L'AGENCE      Jacket        98           336
1821                      TIBI      Jacket       198           670
1822            ALICE + OLIVIA      Jacket        90           306
1823          BY MALENE BIRGER      Jacket       118           490
1824                      DKNY      Jacket        81           151
1825                  SPLENDID      Jacket        80           320
1826          OPENING CEREMONY      Jacket       145           485
1827                RAG & BONE      Jacket        64           320
1828            REBECCA TAYLOR      Jacket       222           445
1829               CINQ À SEPT      Jacket       215          1075
1830                    SANDRO      Jacket       171           285
1831                      MSGM      Jacket       158           785
1832                      TIBI      Jacket       128           845

[1726 rows x 4 columns]

In [11]:
Brand2,Description2,SalePrice2,OriginalPrice2=WS.web_scraper('https://www.theoutnet.com/Search/RenderProductsAsync?ytosQuery=true&linkdepartment=INTL_Tops_CLOTHING&linkdepartmentId=3074457345616677817&department=INTL_Tops_CLOTHING&departmentId=3074457345616677817&gender=&brand=&macro=&micro=&season=&color=&size=&site=&section=&sortRule=&yurirulename=&microcolor=&agerange=&macroMarchio=&page=%i&productsPerPage=96&modelnames=&look=&washtype=&fabric=&prints=&suggestion=false&suggestionValue=&material=&occasion=&weight=&gallery=&colortype=&style=&issale=&heeltype=&wedge=&salesline=&family=&environment=&structure=&authorlocalized=&themecollection=&waist=&stone=&filter=&collection=&price=&facetsvalue=&model=&virtualnavigation=&textSearchFilters=&textSearch=&minMaxPrice=&searchType=&fabricColor=&modelFabric=&itembinding=&totalPages=63&rsiUsed=false&totalItems=5970&partialLoadedItems=96&itemsToLoadOnNextPage=96&siteCode=THEOUTNET_FR&langId=19',63)
df_top=pd.DataFrame([Brand2,Description2,SalePrice2,OriginalPrice2],index=colnames).T
df_top=df_top.drop_duplicates()
df_top.Description='Top'
df_top

                          Brand Description SalePrice OriginalPrice
0                    IRIS & INK         Top       135
1                        CEFINN         Top       121           220
2         McQ Alexander McQueen         Top       121           220
3                      NICHOLAS         Top       213           410
4         McQ Alexander McQueen         Top        69           115
5                  JUST CAVALLI         Top       179           332
7                       RE/DONE         Top       158           285
8             CHINTI AND PARKER         Top       182           365
9         McQ Alexander McQueen         Top       107           195
10               ALICE + OLIVIA         Top       158           316
11                JOHANNA ORTIZ         Top       403           840
12        McQ Alexander McQueen         Top       175           350
13                JOHANNA ORTIZ         Top       416           905
14        McQ Alexander McQueen         Top        78           135
15        McQ Alexander McQueen         Top        77           140
17                   ZIMMERMANN         Top       288           575
18                 APIECE APART         Top       132           275
19        McQ Alexander McQueen         Top        93           155
20                JOHANNA ORTIZ         Top       416           905
21                   ZIMMERMANN         Top       430          1075
22                JOHANNA ORTIZ         Top       333           725
23                 EMILIO PUCCI         Top       296           690
24                     NICHOLAS         Top       185           370
25                      RE/DONE         Top        68           125
26                      RE/DONE         Top       225
27               MICHELLE MASON         Top       177           395
28                      CAMILLA         Top       249           555
29                       CHARLI         Top        79           145
30        McQ Alexander McQueen         Top       134           245
31            CHINTI AND PARKER         Top       137           275
...                         ...         ...       ...           ...
5839                 ALEXACHUNG         Top       178           325
5840                 RAG & BONE         Top        44           173
5841       W118 by WALTER BAKER         Top        42           170
5842                       JOIE         Top        39           264
5843                  BAILEY 44         Top        38           145
5844                       MAJE         Top       117           195
5845             LOVESHACKFANCY         Top        34           112
5846                 RAG & BONE         Top        38           108
5847           BY MALENE BIRGER         Top        20            65
5848             NINETY PERCENT         Top        27            45
5849                     A.L.C.         Top        40           270
5850                     JOSEPH         Top        37            80
5851             NINETY PERCENT         Top        33            55
5852             MANSUR GAVRIEL         Top       120           400
5853           BY MALENE BIRGER         Top        40            80
5854             NINETY PERCENT         Top        33            55
5855                 ENZA COSTA         Top        32           135
5856      DIANE VON FURSTENBERG         Top       108           354
5857                      GANNI         Top        35            69
5858                ZOE KARSSEN         Top        24           120
5860           BY MALENE BIRGER         Top        42           210
5861               PETIT BATEAU         Top        20            40
5862                 RAG & BONE         Top        30           105
5863             NINETY PERCENT         Top        27            45
5864            CURRENT/ELLIOTT         Top        39           190
5866  YUMMIE by HEATHER THOMSON         Top        21            33
5868                     SANDRO         Top        57            95
5869                    BASSIKE         Top        62           125
5870       BAUM UND PFERDGARTEN         Top        28           135
5871               PETIT BATEAU         Top        20            40

[5358 rows x 4 columns]

In [12]:
Brand3,Description3,SalePrice3,OriginalPrice3=WS.web_scraper('https://www.theoutnet.com/Search/RenderProductsAsync?ytosQuery=true&linkdepartment=INTL_Pants_CLOTHING&linkdepartmentId=3074457345616677814&department=INTL_Pants_CLOTHING&departmentId=3074457345616677814&gender=&brand=&macro=&micro=&season=&color=&size=&site=&section=&sortRule=&yurirulename=&microcolor=&agerange=&macroMarchio=&page=%i&productsPerPage=96&modelnames=&look=&washtype=&fabric=&prints=&suggestion=false&suggestionValue=&material=&occasion=&weight=&gallery=&colortype=&style=&issale=&heeltype=&wedge=&salesline=&family=&environment=&structure=&authorlocalized=&themecollection=&waist=&stone=&filter=&collection=&price=&facetsvalue=&model=&virtualnavigation=&textSearchFilters=&textSearch=&minMaxPrice=&searchType=&fabricColor=&modelFabric=&itembinding=&totalPages=28&rsiUsed=false&totalItems=2621&partialLoadedItems=96&itemsToLoadOnNextPage=96&siteCode=THEOUTNET_FR&langId=19',28)
df_pants=pd.DataFrame([Brand3,Description3,SalePrice3,OriginalPrice3],index=colnames).T
df_pants=df_pants.drop_duplicates()
df_pants.Description='Pants'
df_pants

                      Brand Description SalePrice OriginalPrice
0                RAG & BONE       Pants      1040
1                P.E NATION       Pants       235
2        GIAMBATTISTA VALLI       Pants       438           975
3         CHINTI AND PARKER       Pants       178           365
4                   RE/DONE       Pants       290
5     McQ Alexander McQueen       Pants       121           230
6                   RE/DONE       Pants       285
7                   RE/DONE       Pants       290
8                ZIMMERMANN       Pants       350           700
9              EMILIO PUCCI       Pants       355           790
10                    RACIL       Pants       213           435
11             PACO RABANNE       Pants       104           190
12       GIAMBATTISTA VALLI       Pants       408          1020
13               RACHEL ZOE       Pants       198           397
14                   CHARLI       Pants        88           160
15               RAG & BONE       Pants       122           245
16               ZIMMERMANN       Pants       430           860
17             EMILIO PUCCI       Pants       234           520
18           ALICE + OLIVIA       Pants       305           611
19             SONIA RYKIEL       Pants       220           490
21                   CHARLI       Pants        85           155
22          MARY KATRANTZOU       Pants       650
23                    RACIL       Pants       245           490
24                  CAMILLA       Pants       225           500
25                   JOSEPH       Pants       112           225
26                      SEA       Pants       193           430
27                   A.L.C.       Pants       180           400
28            MARKUS LUPFER       Pants        93           195
29             PACO RABANNE       Pants       104           190
30           MICHELLE MASON       Pants       225           500
...                     ...         ...       ...           ...
2545                J BRAND       Pants       652          1305
2546                  GANNI       Pants        74           249
2547                 JOSEPH       Pants        74           245
2548        REBECCA MINKOFF       Pants        54           180
2550                   DKNY       Pants        57           105
2551                 MONROW       Pants        60           200
2552              VALENTINO       Pants       478          1195
2553                   DKNY       Pants        57           105
2555                 SUNDRY       Pants        48           160
2556                 JOSEPH       Pants        64           215
2557           WALTER BAKER       Pants        78           305
2558                    RTA       Pants        58           260
2559               ROKSANDA       Pants       391           890
2560                WILDFOX       Pants        40           135
2561       EMILIA WICKSTEAD       Pants       312           625
2562                    RTA       Pants        40           260
2563      7 FOR ALL MANKIND       Pants        60           200
2564           PAPER London       Pants        54           270
2565                    LNA       Pants        48           155
2566                  BA&SH       Pants        45           180
2567                 JOSEPH       Pants        60           215
2568               ROKSANDA       Pants       214           855
2569                J BRAND       Pants        62           260
2570             RAG & BONE       Pants        58           225
2571                  KORAL       Pants        40           165
2572       BY MALENE BIRGER       Pants        48           243
2573                   DKNY       Pants        28            92
2574               BURBERRY       Pants       105           529
2575                 ADIDAS       Pants        30            60
2576       ADIDAS ORIGINALS       Pants        24            60

[2377 rows x 4 columns]

In [13]:
Brand4,Description4,SalePrice4,OriginalPrice4=WS.web_scraper('https://www.theoutnet.com/Search/RenderProductsAsync?ytosQuery=true&linkdepartment=INTL_Skirts_CLOTHING&linkdepartmentId=3074457345616677816&department=INTL_Skirts_CLOTHING&departmentId=3074457345616677816&gender=&brand=&macro=&micro=&season=&color=&size=&site=&section=&sortRule=&yurirulename=&microcolor=&agerange=&macroMarchio=&page=%i&productsPerPage=96&modelnames=&look=&washtype=&fabric=&prints=&suggestion=false&suggestionValue=&material=&occasion=&weight=&gallery=&colortype=&style=&issale=&heeltype=&wedge=&salesline=&family=&environment=&structure=&authorlocalized=&themecollection=&waist=&stone=&filter=&collection=&price=&facetsvalue=&model=&virtualnavigation=&textSearchFilters=&textSearch=&minMaxPrice=&searchType=&fabricColor=&modelFabric=&itembinding=&totalPages=20&rsiUsed=false&totalItems=1865&partialLoadedItems=96&itemsToLoadOnNextPage=96&siteCode=THEOUTNET_FR&langId=19',20)
df_skirt=pd.DataFrame([Brand4,Description4,SalePrice4,OriginalPrice4],index=colnames).T
df_skirt=df_skirt.drop_duplicates()
df_skirt.Description='Skirt'
df_skirt

                      Brand Description SalePrice OriginalPrice
0                IRIS & INK       Skirt       115
1              APIECE APART       Skirt       157           350
2            ALICE + OLIVIA       Skirt       305           611
3                   RE/DONE       Skirt       159           290
4              APIECE APART       Skirt       199           370
5                  MERLETTE       Skirt       167           390
6                RACHEL ZOE       Skirt       178           356
7                ZIMMERMANN       Skirt       430           860
8                ZIMMERMANN       Skirt       387           860
9              EMILIO PUCCI       Skirt       296           690
10                 NICHOLAS       Skirt       213           410
11           ALICE + OLIVIA       Skirt       385           770
12                   CHARLI       Skirt        82           150
13                 NICHOLAS       Skirt       180           360
14                 NICHOLAS       Skirt       205           410
15               RAG & BONE       Skirt       100           200
16                 NICHOLAS       Skirt       205           410
17             EMILIO PUCCI       Skirt       339           790
18                 NICHOLAS       Skirt       213           410
19             PACO RABANNE       Skirt       225           450
21          MARY KATRANTZOU       Skirt       700
22            JOHANNA ORTIZ       Skirt       535          1140
23               TORY BURCH       Skirt       177           355
25                 NICHOLAS       Skirt       187           360
26                VALENTINO       Skirt      1346          3365
27                  MISSONI       Skirt       580          1290
28                  MASSCOB       Skirt       168           324
30             PACO RABANNE       Skirt      1312          3200
31           ALICE + OLIVIA       Skirt       368           732
32            MARKUS LUPFER       Skirt       447           895
...                     ...         ...       ...           ...
1802           SIMON MILLER       Skirt       112           208
1803         ALICE + OLIVIA       Skirt       112           249
1804                   TIBI       Skirt       124           415
1805                    IRO       Skirt       104           205
1806                  MILLY       Skirt       122           245
1807  DIANE VON FURSTENBERG       Skirt       120           429
1808               LA LIGNE       Skirt        95           475
1809                 THEORY       Skirt        98           335
1810                    AMO       Skirt       105           210
1811             ALEXACHUNG       Skirt       212           380
1812   W118 by WALTER BAKER       Skirt        82           165
1813        3.1 PHILLIP LIM       Skirt       338           705
1814        DOLCE & GABBANA       Skirt      1278          3195
1815             PREEN LINE       Skirt        59           395
1816      BOUTIQUE MOSCHINO       Skirt        72           240
1818      BOUTIQUE MOSCHINO       Skirt       192           385
1819           J.W.ANDERSON       Skirt       312           695
1820           ACNE STUDIOS       Skirt        68           220
1821                   TOME       Skirt       219           730
1822                 JOSEPH       Skirt       145           485
1823         NINETY PERCENT       Skirt        39            65
1824                   MSGM       Skirt       140           470
1825                 VINCE.       Skirt        48           315
1826         NINETY PERCENT       Skirt        36            60
1827                    RTA       Skirt        40           180
1828               FIORUCCI       Skirt        38           180
1829       ADIDAS ORIGINALS       Skirt        20            80
1830         NINETY PERCENT       Skirt        30            50
1831                  GANNI       Skirt        32           129
1832             IRIS & INK       Skirt        20           100

[1728 rows x 4 columns]

In [14]:
def mode_agg(x):
    return(''.join(x.mode().values.tolist()))

In [15]:
df_skirt=df_skirt.drop((df_skirt[df_skirt.OriginalPrice==''].index.tolist()),axis=0)
df_skirt

                      Brand Description SalePrice OriginalPrice
1              APIECE APART       Skirt       157           350
2            ALICE + OLIVIA       Skirt       305           611
3                   RE/DONE       Skirt       159           290
4              APIECE APART       Skirt       199           370
5                  MERLETTE       Skirt       167           390
6                RACHEL ZOE       Skirt       178           356
7                ZIMMERMANN       Skirt       430           860
8                ZIMMERMANN       Skirt       387           860
9              EMILIO PUCCI       Skirt       296           690
10                 NICHOLAS       Skirt       213           410
11           ALICE + OLIVIA       Skirt       385           770
12                   CHARLI       Skirt        82           150
13                 NICHOLAS       Skirt       180           360
14                 NICHOLAS       Skirt       205           410
15               RAG & BONE       Skirt       100           200
16                 NICHOLAS       Skirt       205           410
17             EMILIO PUCCI       Skirt       339           790
18                 NICHOLAS       Skirt       213           410
19             PACO RABANNE       Skirt       225           450
22            JOHANNA ORTIZ       Skirt       535          1140
23               TORY BURCH       Skirt       177           355
25                 NICHOLAS       Skirt       187           360
26                VALENTINO       Skirt      1346          3365
27                  MISSONI       Skirt       580          1290
28                  MASSCOB       Skirt       168           324
30             PACO RABANNE       Skirt      1312          3200
31           ALICE + OLIVIA       Skirt       368           732
32            MARKUS LUPFER       Skirt       447           895
33             REDValentino       Skirt       212           425
34               ZIMMERMANN       Skirt       375           750
...                     ...         ...       ...           ...
1802           SIMON MILLER       Skirt       112           208
1803         ALICE + OLIVIA       Skirt       112           249
1804                   TIBI       Skirt       124           415
1805                    IRO       Skirt       104           205
1806                  MILLY       Skirt       122           245
1807  DIANE VON FURSTENBERG       Skirt       120           429
1808               LA LIGNE       Skirt        95           475
1809                 THEORY       Skirt        98           335
1810                    AMO       Skirt       105           210
1811             ALEXACHUNG       Skirt       212           380
1812   W118 by WALTER BAKER       Skirt        82           165
1813        3.1 PHILLIP LIM       Skirt       338           705
1814        DOLCE & GABBANA       Skirt      1278          3195
1815             PREEN LINE       Skirt        59           395
1816      BOUTIQUE MOSCHINO       Skirt        72           240
1818      BOUTIQUE MOSCHINO       Skirt       192           385
1819           J.W.ANDERSON       Skirt       312           695
1820           ACNE STUDIOS       Skirt        68           220
1821                   TOME       Skirt       219           730
1822                 JOSEPH       Skirt       145           485
1823         NINETY PERCENT       Skirt        39            65
1824                   MSGM       Skirt       140           470
1825                 VINCE.       Skirt        48           315
1826         NINETY PERCENT       Skirt        36            60
1827                    RTA       Skirt        40           180
1828               FIORUCCI       Skirt        38           180
1829       ADIDAS ORIGINALS       Skirt        20            80
1830         NINETY PERCENT       Skirt        30            50
1831                  GANNI       Skirt        32           129
1832             IRIS & INK       Skirt        20           100

[1703 rows x 4 columns]

In [16]:
df_skirt.OriginalPrice=df_skirt.OriginalPrice.astype('int')
df_skirt.SalePrice=df_skirt.SalePrice.astype('int')
df_skirt1=df_skirt.groupby('Brand').agg({'Description':mode_agg,'SalePrice':'mean','OriginalPrice':'mean'}).reset_index().copy()
df_skirt1

                          Brand Description    SalePrice  OriginalPrice
0               3.1 PHILLIP LIM       Skirt   284.833333     623.333333
1                           3x1       Skirt   149.333333     299.000000
2             7 FOR ALL MANKIND       Skirt   105.666667     263.333333
3                        A.L.C.       Skirt   200.125000     454.375000
4                        A.P.C.       Skirt    95.000000     175.000000
5                    A.W.A.K.E.       Skirt   245.000000     490.000000
6                  ACNE STUDIOS       Skirt   164.444444     350.555556
7                   ADAM LIPPES       Skirt   351.666667     898.250000
8                         ADEAM       Skirt   251.000000     535.000000
9              ADIDAS ORIGINALS       Skirt    20.000000      80.000000
10                       AGNONA       Skirt   510.555556    1231.555556
11                        ALAÏA       Skirt   882.000000    2716.666667
12             ALBERTA FERRETTI       Skirt   443.750000     941.250000
13                   ALEXACHUNG       Skirt   164.333333     310.833333
14            ALEXANDER MCQUEEN       Skirt  1174.000000    2579.600000
15               ALEXANDER WANG       Skirt   263.750000     550.000000
16              ALEXANDERWANG.T       Skirt   157.714286     340.000000
17               ALICE + OLIVIA       Skirt   283.354839     618.709677
18                 ALICE McCALL       Skirt   147.000000     267.500000
19                    ALTUZARRA       Skirt   450.500000     962.916667
20               AMANDA WAKELEY       Skirt   327.166667     776.666667
21                        AMIRI       Skirt   567.500000    1172.500000
22                          AMO       Skirt   105.000000     210.000000
23           ANN DEMEULEMEESTER       Skirt   380.272727     838.909091
24                 ANNA OCTOBER       Skirt   197.000000     345.500000
25                    ANNA QUAN       Skirt   217.333333     435.000000
26                     ANNA SUI       Skirt   252.846154     526.153846
27                  ANTIK BATIK       Skirt   117.600000     219.800000
28              ANTONIO BERARDI       Skirt   370.666667     879.000000
29                 APIECE APART       Skirt   178.000000     360.000000
..                          ...         ...          ...            ...
234                STAND STUDIO       Skirt   169.333333     332.333333
235                 STELLA JEAN       Skirt   307.900000     641.250000
236            STELLA McCARTNEY       Skirt   324.888889     791.111111
237            TEMPERLEY LONDON       Skirt   518.833333    1245.000000
238                   THE RANGE       Skirt   100.000000     189.666667
239                     THE ROW       Skirt   736.000000    1887.500000
240                      THEORY       Skirt   176.866667     384.000000
241                 THOM BROWNE       Skirt   770.000000    1540.000000
242         THREE GRACES LONDON       Skirt   345.000000     690.000000
243                        TIBI       Skirt   262.090909     587.727273
244                    TOM FORD       Skirt   953.000000    2276.666667
245                 TOMAS MAIER       Skirt   279.666667     696.666667
246                        TOME       Skirt   212.750000     531.250000
247                  TORY BURCH       Skirt   421.000000     835.833333
248                ULLA JOHNSON       Skirt   310.000000     620.000000
249                   VALENTINO       Skirt  1053.500000    3129.318182
250               VANESSA BRUNO       Skirt   141.250000     308.750000
251              VERONICA BEARD       Skirt   178.166667     436.666667
252                     VERSACE       Skirt   294.750000     696.250000
253              VERSUS VERSACE       Skirt   175.230769     341.153846
254                   VETEMENTS       Skirt   482.500000    1715.000000
255            VICTORIA BECKHAM       Skirt   603.333333    1347.555556
256  VICTORIA, VICTORIA BECKHAM       Skirt   238.615385     496.538462
257                   VILSHENKO       Skirt   299.666667     666.666667
258                      VINCE.       Skirt   198.375000     362.812500
259                     VIONNET       Skirt   238.000000     944.000000
260        W118 by WALTER BAKER       Skirt    92.400000     181.000000
261                WALTER BAKER       Skirt   179.400000     357.000000
262                  ZIMMERMANN       Skirt   489.000000    1000.666667
263                 ÊTRE CÉCILE       Skirt   128.333333     256.666667

[264 rows x 4 columns]

In [17]:
df_dress=df_dress.drop((df_dress[df_dress.OriginalPrice==''].index.tolist()),axis=0)
df_dress.OriginalPrice=df_dress.OriginalPrice.astype('int')
df_dress.SalePrice=df_dress.SalePrice.astype('int')
df_dress1=df_dress.groupby('Brand').agg({'Description':mode_agg,'SalePrice':'mean','OriginalPrice':'mean'}).reset_index().copy()
df_dress1

                          Brand Description    SalePrice  OriginalPrice
0               3.1 PHILLIP LIM       Dress   435.750000    1004.583333
1                           3x1       Dress    70.000000     285.000000
2             7 FOR ALL MANKIND       Dress   130.000000     260.000000
3                        A.L.C.       Dress   242.684211     551.315789
4                        A.P.C.       Dress   114.000000     220.000000
5                    A.W.A.K.E.       Dress   388.000000     775.000000
6                  ACNE STUDIOS       Dress   263.583333     624.166667
7                   ADAM LIPPES       Dress   502.833333    1335.375000
8                         ADEAM       Dress   542.000000    1106.250000
9                      AG JEANS       Dress   155.000000     311.000000
10                       AGNONA       Dress   694.714286    1505.714286
11                        AKRIS       Dress  1005.666667    2580.833333
12                        ALAÏA       Dress  1380.000000    3448.750000
13             ALBERTA FERRETTI       Dress  1044.320000    2207.000000
14              ALESSANDRA RICH       Dress  1724.000000    4310.000000
15                   ALEXACHUNG       Dress   237.416667     496.111111
16            ALEXANDER MCQUEEN       Dress  2029.950000    4292.000000
17               ALEXANDER WANG       Dress   513.148148    1341.481481
18              ALEXANDERWANG.T       Dress   177.142857     402.250000
19           ALEXANDRE VAUTHIER       Dress  1814.000000    4030.000000
20                       ALEXIS       Dress   171.000000     558.333333
21               ALEXIS MABILLE       Dress  1754.000000    4175.000000
22               ALICE + OLIVIA       Dress   254.842105     594.684211
23                 ALICE McCALL       Dress   195.619048     479.761905
24                    ALTUZARRA       Dress   654.058824    1479.411765
25               AMANDA WAKELEY       Dress   428.181818    1143.636364
26             AMERICAN VINTAGE       Dress    96.000000     160.000000
27                        AMIRI       Dress   485.142857    1029.285714
28                   ANINE BING       Dress   129.666667     261.666667
29           ANN DEMEULEMEESTER       Dress   407.000000     864.200000
..                          ...         ...          ...            ...
326                ULLA JOHNSON       Dress   346.000000     702.333333
327                   VALENTINO       Dress  1353.948148    3943.770370
328               VANESSA BRUNO       Dress   203.046512     450.488372
329         VANESSA BRUNO ATHE'       Dress   150.000000     300.000000
330              VANESSA SEWARD       Dress   203.600000     481.000000
331                        VEDA       Dress   267.000000     495.000000
332  VELVET by GRAHAM & SPENCER       Dress    98.000000     418.000000
333              VERONICA BEARD       Dress   273.640000     591.200000
334                     VERSACE       Dress   620.090909    1716.363636
335          VERSACE COLLECTION       Dress   328.285714     818.571429
336             VERSACE TRIBUTE       Dress   598.000000    2990.000000
337              VERSUS VERSACE       Dress   278.285714     621.071429
338                   VETEMENTS       Dress   665.166667    1473.333333
339              VICTOR GLEMAUD       Dress   288.000000     575.000000
340            VICTORIA BECKHAM       Dress   906.628571    1983.571429
341  VICTORIA, VICTORIA BECKHAM       Dress   324.666667     657.708333
342                   VILSHENKO       Dress   572.000000    1410.000000
343                      VINCE.       Dress   213.000000     423.235294
344                     VIONNET       Dress   545.000000    2208.500000
345          VIX PAULA HERMANNY       Dress   116.666667     281.000000
346        W118 by WALTER BAKER       Dress   113.642857     250.714286
347                WALTER BAKER       Dress   135.400000     264.000000
348                WE ARE LEONE       Dress   254.000000     548.000000
349                     WOLFORD       Dress   118.833333     201.666667
350                   ZAC POSEN       Dress   983.263158    2936.710526
351               ZAC ZAC POSEN       Dress   404.400000     891.600000
352                  ZIMMERMANN       Dress   537.420290    1121.731884
353                ZUHAIR MURAD       Dress  2008.444444    5905.222222
354                      byTIMO       Dress   128.000000     268.500000
355                 ÊTRE CÉCILE       Dress   152.333333     309.333333

[356 rows x 4 columns]

In [18]:
df_pants=df_pants.drop((df_pants[df_pants.OriginalPrice==''].index.tolist()),axis=0)
df_pants.OriginalPrice=df_pants.OriginalPrice.astype('int')
df_pants.SalePrice=df_pants.SalePrice.astype('int')
df_pants1=df_pants.groupby('Brand').agg({'Description':mode_agg,'SalePrice':'mean','OriginalPrice':'mean'}).reset_index().copy()
df_pants1

                            Brand Description   SalePrice  OriginalPrice
0                 3.1 PHILLIP LIM       Pants  254.187500     577.187500
1                             3x1       Pants  207.666667     415.833333
2               7 FOR ALL MANKIND       Pants  198.666667     417.777778
3                          A.L.C.       Pants  205.750000     466.250000
4                    ACNE STUDIOS       Pants  219.200000     475.500000
5                     ADAM LIPPES       Pants  337.523810     815.714286
6                           ADEAM       Pants  342.666667     746.666667
7                          ADIDAS       Pants   36.000000      71.666667
8                ADIDAS ORIGINALS       Pants   61.500000     120.833333
9      ADIDAS by STELLA McCARTNEY       Pants  107.800000     185.000000
10                       AG JEANS       Pants  193.833333     398.444444
11                         AGNONA       Pants  386.200000     872.000000
12                          AKRIS       Pants  424.666667    1008.000000
13                          ALAÏA       Pants  970.000000    2425.000000
14               ALBERTA FERRETTI       Pants  375.833333     752.500000
15                     ALEXACHUNG       Pants  203.166667     403.333333
16              ALEXANDER MCQUEEN       Pants  540.333333    1218.500000
17                 ALEXANDER WANG       Pants  296.692308     772.692308
18                ALEXANDERWANG.T       Pants  225.687500     480.625000
19                         ALEXIS       Pants  268.000000     762.500000
20                 ALICE + OLIVIA       Pants  190.642857     423.571429
21                      ALTUZARRA       Pants  296.111111     665.555556
22                 AMANDA WAKELEY       Pants  237.500000     581.250000
23               AMERICAN VINTAGE       Pants   79.200000     132.000000
24                          AMIRI       Pants  878.000000    2195.000000
25                     ANINE BING       Pants  102.000000     205.000000
26             ANN DEMEULEMEESTER       Pants  315.347826     668.086957
27                      ANNA QUAN       Pants  202.166667     469.166667
28                       ANNA SUI       Pants  266.000000     522.500000
29                    ANTIK BATIK       Pants  121.400000     226.000000
..                            ...         ...         ...            ...
277                       THE ROW       Pants  732.153846    1602.846154
278                    THE UPSIDE       Pants   89.666667     163.333333
279                        THEORY       Pants  161.115942     353.768116
280                   THOM BROWNE       Pants  382.000000     955.000000
281                          TIBI       Pants  246.294118     552.058824
282                      TOM FORD       Pants  494.750000    1096.250000
283                   TOMAS MAIER       Pants  192.000000     410.000000
284                          TOME       Pants  222.285714     607.857143
285                    TORY BURCH       Pants  162.700000     342.000000
286                  ULLA JOHNSON       Pants  216.666667     433.333333
287                     VALENTINO       Pants  553.263158    1317.105263
288                 VANESSA BRUNO       Pants  119.933333     286.666667
289                VERONICA BEARD       Pants  212.000000     482.142857
290                       VERSACE       Pants  267.875000     770.625000
291            VERSACE COLLECTION       Pants  132.000000     279.166667
292                VERSUS VERSACE       Pants  192.000000     385.000000
293                     VETEMENTS       Pants  561.000000    1100.000000
294              VICTORIA BECKHAM       Pants  434.000000    1010.200000
295    VICTORIA, VICTORIA BECKHAM       Pants  264.821429     555.000000
296                        VINCE.       Pants  218.733333     387.000000
297  VIVIENNE WESTWOOD ANGLOMANIA       Pants  194.000000     405.000000
298            VIX PAULA HERMANNY       Pants   69.000000     230.000000
299          W118 by WALTER BAKER       Pants   90.000000     180.000000
300                  WALTER BAKER       Pants  269.600000     548.000000
301                       WILDFOX       Pants   64.933333     134.000000
302                       WOLFORD       Pants   96.000000     162.500000
303                    ZIMMERMANN       Pants  336.218750     662.906250
304                   ZOE KARSSEN       Pants   48.000000     120.000000
305               Ç X MIRA MIKATI       Pants  130.000000     435.000000
306                   ÊTRE CÉCILE       Pants  105.000000     215.000000

[307 rows x 4 columns]

In [19]:
df_jacket=df_jacket.drop((df_jacket[df_jacket.OriginalPrice==''].index.tolist()),axis=0)
df_jacket.OriginalPrice=df_jacket.OriginalPrice.astype('int')
df_jacket.SalePrice=df_jacket.SalePrice.astype('int')
df_jacket1=df_jacket.groupby('Brand').agg({'Description':mode_agg,'SalePrice':'mean','OriginalPrice':'mean'}).reset_index().copy()
df_jacket1

                          Brand Description    SalePrice  OriginalPrice
0               3.1 PHILLIP LIM      Jacket   320.250000     763.437500
1                           3x1      Jacket   207.500000     415.000000
2             7 FOR ALL MANKIND      Jacket   222.600000     526.000000
3                        A.L.C.      Jacket   312.875000     758.125000
4                  ACNE STUDIOS      Jacket   518.750000    1037.500000
5                   ADAM LIPPES      Jacket   470.600000    1241.000000
6                         ADEAM      Jacket   775.500000    1672.500000
7                      AG JEANS      Jacket   165.000000     300.000000
8                        AGNONA      Jacket   592.000000    1510.000000
9                         AINEA      Jacket   207.000000     434.500000
10                        AKRIS      Jacket   891.666667    2365.000000
11             ALBERTA FERRETTI      Jacket   542.500000    1085.000000
12              ALESSANDRA RICH      Jacket  1128.000000    2820.000000
13                   ALEXACHUNG      Jacket   255.285714     534.285714
14            ALEXANDER MCQUEEN      Jacket  1228.500000    2651.000000
15               ALEXANDER WANG      Jacket   437.846154     998.846154
16              ALEXANDERWANG.T      Jacket   257.125000     565.625000
17               ALICE + OLIVIA      Jacket   340.000000     732.380952
18                 ALICE McCALL      Jacket   265.000000     590.000000
19                    ALTUZARRA      Jacket   674.500000    1394.166667
20               AMANDA WAKELEY      Jacket   374.800000     923.000000
21             AMERICAN VINTAGE      Jacket    93.000000     155.000000
22                        AMIRI      Jacket   623.600000    1359.000000
23                   ANINE BING      Jacket   125.000000     250.000000
24           ANN DEMEULEMEESTER      Jacket   590.629630    1304.814815
25                 ANNA OCTOBER      Jacket   326.500000     653.000000
26                    ANNA QUAN      Jacket   335.000000     670.000000
27                     ANNA SUI      Jacket   310.062500     641.062500
28                  ANTIK BATIK      Jacket   257.400000     486.200000
29              ANTONIO BERARDI      Jacket   704.000000    2135.000000
..                          ...         ...          ...            ...
238                        TIBI      Jacket   300.142857     730.714286
239                    TOM FORD      Jacket  1085.000000    2582.500000
240                 TOMAS MAIER      Jacket   587.000000    1957.500000
241                        TOME      Jacket   387.000000     775.000000
242                  TORY BURCH      Jacket   284.428571     665.000000
243     TRE by NATALIE RATABESI      Jacket   350.000000     700.000000
244                ULLA JOHNSON      Jacket   355.000000     710.000000
245    VAKKO by PIAZZA SEMPIONE      Jacket   175.000000     875.000000
246                   VALENTINO      Jacket  1331.600000    3894.000000
247               VANESSA BRUNO      Jacket   204.111111     463.055556
248                        VEDA      Jacket   440.000000     848.750000
249              VERONICA BEARD      Jacket   296.157895     658.947368
250                     VERSACE      Jacket   590.875000    1498.750000
251          VERSACE COLLECTION      Jacket   309.700000     656.000000
252              VERSUS VERSACE      Jacket   382.000000     882.142857
253                   VETEMENTS      Jacket  1215.200000    2655.000000
254            VICTORIA BECKHAM      Jacket   878.750000    2027.500000
255  VICTORIA, VICTORIA BECKHAM      Jacket   383.583333     853.333333
256                   VILSHENKO      Jacket   371.000000     865.000000
257                      VINCE.      Jacket   394.888889     744.444444
258        W118 by WALTER BAKER      Jacket   333.714286     717.428571
259                WALTER BAKER      Jacket   308.800000     618.000000
260                WE ARE LEONE      Jacket   294.750000     592.500000
261                     WILDFOX      Jacket    82.571429     176.428571
262                YVES SALOMON      Jacket   981.000000    2375.000000
263                   ZAC POSEN      Jacket  1062.666667    2610.000000
264                  ZIMMERMANN      Jacket   705.444444    1423.055556
265                 ZOE KARSSEN      Jacket   195.000000     390.000000
266                ZUHAIR MURAD      Jacket  1417.000000    3150.000000
267                 ÊTRE CÉCILE      Jacket   175.000000     350.000000

[268 rows x 4 columns]

In [20]:
df_top=df_top.drop((df_top[df_top.OriginalPrice==''].index.tolist()),axis=0)
df_top.OriginalPrice=df_top.OriginalPrice.astype('int')
df_top.SalePrice=df_top.SalePrice.astype('int')
df_top1=df_top.groupby('Brand').agg({'Description':mode_agg,'SalePrice':'mean','OriginalPrice':'mean'}).reset_index().copy()
df_top1

                          Brand Description    SalePrice  OriginalPrice
0               3.1 PHILLIP LIM         Top   173.205882     415.882353
1                           3x1         Top   115.375000     231.000000
2             7 FOR ALL MANKIND         Top   109.125000     231.250000
3                        A.L.C.         Top   148.684211     324.473684
4                    A.W.A.K.E.         Top   213.333333     423.333333
5                  ACNE STUDIOS         Top   155.300000     332.500000
6                   ADAM LIPPES         Top   289.869565     644.130435
7                         ADEAM         Top   330.090909     671.363636
8              ADIDAS ORIGINALS         Top    39.000000      70.000000
9                      AG JEANS         Top    64.200000     119.800000
10                       AGNONA         Top   358.800000     754.000000
11                        AKRIS         Top   531.000000    1202.500000
12                        ALAÏA         Top   548.500000    1400.000000
13             ALBERTA FERRETTI         Top   501.000000    1002.500000
14                   ALEXACHUNG         Top   120.317073     236.219512
15            ALEXANDER MCQUEEN         Top   671.571429    1432.142857
16               ALEXANDER WANG         Top   240.428571     558.190476
17              ALEXANDERWANG.T         Top   137.053571     293.321429
18                       ALEXIS         Top    78.000000     305.000000
19               ALICE + OLIVIA         Top   150.637681     324.014493
20                 ALICE McCALL         Top   119.272727     258.636364
21                         ALIX         Top    96.466667     183.333333
22             ALL THINGS MOCHI         Top    50.000000     170.000000
23                    ALTUZARRA         Top   256.142857     592.142857
24               AMANDA WAKELEY         Top   231.142857     557.142857
25             AMERICAN VINTAGE         Top    64.285714     107.142857
26                        AMIRI         Top   296.200000     609.000000
27                   ANINE BING         Top    56.000000     112.000000
28           ANN DEMEULEMEESTER         Top   317.650000     699.666667
29                 ANNA OCTOBER         Top   273.000000     530.000000
..                          ...         ...          ...            ...
314                        TIBI         Top   176.097222     404.305556
315                    TOM FORD         Top   773.166667    1862.500000
316                 TOMAS MAIER         Top   218.333333     528.333333
317                        TOME         Top   202.652174     490.434783
318                  TORY BURCH         Top   174.857143     380.714286
319                ULLA JOHNSON         Top   213.000000     482.000000
320                   VALENTINO         Top   532.538462    1462.307692
321               VANESSA BRUNO         Top   148.235294     327.352941
322         VANESSA BRUNO ATHE'         Top    42.000000     170.000000
323  VELVET by GRAHAM & SPENCER         Top    70.000000     140.000000
324              VERONICA BEARD         Top   163.590909     371.136364
325                     VERSACE         Top   259.333333     690.833333
326          VERSACE COLLECTION         Top   391.200000     816.000000
327              VERSUS VERSACE         Top   133.400000     256.666667
328            VICTORIA BECKHAM         Top   399.333333     857.555556
329  VICTORIA, VICTORIA BECKHAM         Top   189.000000     377.782609
330                   VILSHENKO         Top   208.000000     440.000000
331                      VINCE.         Top   155.609756     275.731707
332           VIVIENNE WESTWOOD         Top   351.500000     747.500000
333        W118 by WALTER BAKER         Top    77.200000     168.666667
334                WALTER BAKER         Top    95.166667     190.000000
335                     WILDFOX         Top    66.500000     133.000000
336                     WOLFORD         Top   113.166667     181.250000
337   YUMMIE by HEATHER THOMSON         Top    21.000000      33.000000
338                   ZAC POSEN         Top   361.000000     785.000000
339                  ZIMMERMANN         Top   291.011236     569.606742
340                 ZOE KARSSEN         Top    37.800000      91.000000
341                ZUHAIR MURAD         Top  1057.000000    2350.000000
342                      byTIMO         Top   107.500000     235.000000
343                 ÊTRE CÉCILE         Top    65.500000     129.250000

[344 rows x 4 columns]

In [21]:
df_dress1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\DressTON.csv',index=False)
df_pants1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\PantsTON.csv',index=False)
df_jacket1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\JacketTON.csv',index=False)
df_top1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\TopTON.csv',index=False)
df_skirt1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\SkirtTON.csv',index=False)