In [1]:
import requests as r
from bs4 import BeautifulSoup as BS
import pandas as pd
import re
import time as t

In [2]:
headers={'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
         'accept-encoding': 'gzip, deflate, br',
         'accept-language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
         'cache-control': 'max-age=0',
         'cookie': '_qubitTracker=hei2mrvo6e8-0k2d6y6d4-jdr2t40; country_iso=FR; channel=intl; lang_iso=fr; geoIP=FR; deviceType=Desktop; _abck=CB5BE5B5AE74DB3EA7118BDD9D911F5A~0~YAAQJfMUAhPQyPRtAQAAy4tnHAITZEZ4J/X1yElFgd6VQ0KYrdkoK+IZrP3hmDw96AnaGb4ygzYDCmt4H+zQIX6D/Ifm8s6r1mz7kwx24uDUQtGmawydlxhVvvnJuSEYMWzjdWr/7aLcoQ1tW9XWtbUqdPuXnSGHvA/vEJk17vi6WE8UdaEh0moARJqB4exhh3zQcZTv38hQtiG44yNoH5hF5wv/ngp03yxrTfrvIy1SiYyccyDeBGlLKK7P3Ay19eNfSfbf94hEcJqTUv1To3Zf7KTAvyw4VHRxBJAP+9RYXBX4UkdLvQ==~-1~-1~-1; JSESSIONID_INTL=B63BA587763FDD950C4382916D90D47B.nap-intl-sav-08; qb_generic=:W4cZ463:.net-a-porter.com; s_cc=true; s_fid=026DBA5C593AFD64-1CCDF04A51C21C13; s_ppv=-; s_sq=%5B%5BB%5D%5D; s_vi=[CS]v1|2EDCB94985158000-400648FD01FFEA45[CE]; _gcl_au=1.1.953636057.1572434581; _ga=GA1.2.2094326186.1572434581; _fbp=fb.1.1572434581457.1225732642; yOrbRD=guid%3Dcb15523a-6195-48b8-98ac-25019dc9e34d; _ym_d=1572434582; _ym_uid=1572434582136409552; LPVID=M3M2MwMTA3NTQ4MGFjZjZl; t060a-dbcookie=1; _gid=GA1.2.1207788891.1572522013; bm_sz=77C3C512F71D7590F15FA81A33AC0D9B~YAAQQVfIF5m4JdttAQAAwBYWJgX/dCYeVqOW+ur5GBp8ZIRrayFBBqhsuYYNtQTI+4xllNqUqk05mykdC0xOWqUKQy0S5XDzFD+LEXJr4zekFIPBwPK6c4M3D0Y7CcBt+7fM0pr887uUilHP8+i4V0uTmpn6FdZbrENmrW9htwwnFEpSOpc2Jb8mwcjWg0v7rn2hIzMp; _ym_isad=2; bm_mi=62FB042702217C9644CFD6788EE7DFBC~S3sLLBrUpBjs/jNGgS9MFOVZMLaCiD4/MFUxJEugtY/IdVwHmSGGrEWZXg9rpQBVv0yWKCjEKm2FHc0ewYamJWLKJYUkg9XRNUvQ966UF0UeW2UfOcbCAHQat2BdDbmaMRyW077SAEskWpGXfrrdAO7YAzGAuuOLq8OoU36MrJ5+2qsNbe8hN0vnBl6sPZyxE8NMyzn7wpBnvVVQiBJw2bNcQ36Wqu14qAAgz7RHmwDa32tp3m5Oax4EaJRebp8TLrTpEd6LVvnbTk33lue2r0Q/cUCxKp6v/vCf/DASv8Y=; _qst_s=4; ak_bmsc=1B191FD3A157F2F452FD76047649880B0214F3255F1600009C0DBC5D80A72221~pl9sXVVw1m8LM0AbNFLkVkefcSchQVUqMKhQgVKTg89+alXrH9XdzQBflmMUOCjYsbEkGwqUVgEs6xrE8pvLqXbe+cBpBq2x8vizQLuwL8knOdkTnW0mlDs5U/pWYX44kCzZIw1e1/glvATstnIUygRsWbnOqkCtsvV7MuGFUzE3HSkwG36F2XaPcf/RmuEunl55JoikAqE0lupr3kRcHDxDaC7GSFeIjttCiiJ0RRLFfpD/DdI2V+LAhtB5p9vq3i; _qst=%5B4%2C0%5D; WebAn_navigation.previousPage=homepage; s_invisit=true; s_vnum=1575154800385%26vn%3D2; s_cm_mmc=GoogleFR%E2%80%94c-_-NAP_FR_FR-_-Brand-_-Net%20A%20Porter_Exact-_-net%20a%20porter_e_aud-314946097399%3Akwd-394219513_INTL; _gcl_aw=GCL.1572605344.Cj0KCQjwr-_tBRCMARIsAN413WS6E0gjHL5sgqkxm-9uPuL62zw_82_inlUqhl52LBLkLjAGbtgeNxkaAuz9EALw_wcB; _gcl_dc=GCL.1572605344.Cj0KCQjwr-_tBRCMARIsAN413WS6E0gjHL5sgqkxm-9uPuL62zw_82_inlUqhl52LBLkLjAGbtgeNxkaAuz9EALw_wcB; s_ev6=%5B%5B%27GoogleFR%25u2014c%27%2C%271572434581133%27%5D%2C%5B%27GoogleFR%25u2014c%27%2C%271572434581146%27%5D%2C%5B%27GoogleFR%25u2014c%27%2C%271572605343263%27%5D%2C%5B%27GoogleFR%25u2014c%27%2C%271572605344236%27%5D%2C%5B%27GoogleFR%25u2014c%27%2C%271572605344251%27%5D%5D; _gac_UA-4866101-1=1.1572605344.Cj0KCQjwr-_tBRCMARIsAN413WS6E0gjHL5sgqkxm-9uPuL62zw_82_inlUqhl52LBLkLjAGbtgeNxkaAuz9EALw_wcB; LPSID-73583570=MMYQOWP7T5a9D_oxT50Teg; s_cm_sp=topnav-_-clothing-_-dresses; _qsst_s=1572605678731; x_qtag_1984205=EYz7_Xgo_LGcDPCcQ1B4ZYqiCXlRWxPZFh6fC1SFSefeeOeMaAoVHEALw_wcB*+Cj0KCQjw6eTtBRDdARIsANZWjYZCwAIi*Net+A+Porter_Exact*net+a+porter_e_aud*394219513_INTL*392207328874*porter.com*+GoogleFR*NAP_FR_FR*clothing*.cm_mmc*.gclsrc*.gclid*+aw.ds*Brand*Vnet*v94c*jkwd@*a*Qsc*Q*j4*C*B4*C*P8*5-1572605342625*4-*7-fr/*Y*9-*@15--a-@6-/fr/fr/*k*@10-*@7-*vE2*v80*@16--_-@8--_-@14--_-@2--_-@3--@5-*@17--@4-*@12-*@1--@0-*@11-*@13-*Y*A1572434579513*b*C*a*Mnet-a-@6-/fr/fr/*k*@10-*@7-*vE2*v80*@16--_-@8--_-@14--_-@2--_-@3--@5-*@17--@4-*@12-*@1--@0-*@11-*@13-*Y*9-*@15--a-@6-/fr/fr/d/Shop/Clothing/All*kcm_sp*+topnav-_-@9--_-all@9-*.pn*+3*.npp*+60*.image_view*+product*.dscroll*+0*Y*A1572522009077*b*E*C*F*Q*@15--a-@6-/fr/fr/*k*@10-*@7-*vE2*v80*@16--_-@8--_-@14--_-@2--_-@3--314946097399*@17--@4-*@12-*+Cj0KCQjwr-_tBRCMARIsAN413WS6E0gjHL5sgqkxm-9uPuL62zw_82_inlUqhl52LBLkLjAGbtgeNxkaAuz9EALw_wcB*@11-*@13-*Y*Q__v*z; _qPageNum_net_a_porter_live=2; _qsst=1572605679593; qb_session=3:1:42:CPMm=D&D5W0=B:0:W4mlTce:0:0:0:0:.net-a-porter.com; qb_permanent=hei2mrvo6e8-0k2d6y6d4-jdr2t40:8:3:4:2:0::0:1:0:BduXKV:BdvA7w:A::::195.134.167.217:paris:1706:france:FR:48.8894:2.31494:paris:250075:ile-de-france:34979:migrated|1572605680093:CPMm=Gx=I=/zR=LZ&D5W0=LH=C=Bv1a=Fp:gGi:W4mmlnd:W4mlTce:0:0:0::0:0:.net-a-porter.com:0; QSI_HistorySession=https%3A%2F%2Fwww.net-a-porter.com%2Ffr%2Ffr%2Fd%2FShop%2FClothing%2FDresses%3Fcm_sp%3Dtopnav-_-clothing-_-dresses%26pn%3D1%26npp%3D60%26image_view%3Dproduct%26dScroll%3D0~1572605360636%7Chttps%3A%2F%2Fwww.net-a-porter.com%2Ffr%2Ffr%2Fd%2FShop%2FClothing%2FDresses%3Fcm_sp%3Dtopnav-_-clothing-_-dresses%26pn%3D1%26npp%3D60%26image_view%3Dproduct%26dscroll%3D0~1572605680980; QSI_SI_80M0mISiaEnDyLP_intercept=true; bm_sv=E3C4F1C926CF8BBDF8AA2230C9E2E63B~GktZPaPKvbb1wcOpPzUHJ8LOjO/h3VUoYeQSD54OCPoY5345VUNlPr+Q5rs4AyMetiSEwCyr1bqfiQherS/Jpory4gsmWBIiGRHgz+nowfvsnnS6L1F93b4svOB0tNYUOm6sVaKNR9oOvExvdX4QucaZHFinClffkYtcYBiwwIE=; prevPage=Clothing%20-%20Dresses%20%3Apage02; s_nr=1572605769790-Repeat',
         'referer': 'https://www.net-a-porter.com/fr/fr/?&cm_mmc=GoogleFR%E2%80%94c-_-NAP_FR_FR-_-Brand-_-Net+A+Porter_Exact-_-net+a+porter_e_aud-314946097399:kwd-394219513_INTL&gclid=Cj0KCQjwr-_tBRCMARIsAN413WS6E0gjHL5sgqkxm-9uPuL62zw_82_inlUqhl52LBLkLjAGbtgeNxkaAuz9EALw_wcB&gclsrc=aw.ds',
         'sec-fetch-mode': 'navigate',
         'sec-fetch-site': 'same-origin',
         'sec-fetch-user': '?1',
         'upgrade-insecure-requests': '1',
         'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.83'}

In [3]:
table_brand=[]
for i in range(1,68):
    if i%2==0:
            t.sleep(2)
    url=f'https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Dresses?cm_sp=topnav-_-clothing-_-dresses&pn=%i&npp=60&image_view=product&dscroll=0'
    lst=BS(r.get(url,headers=headers).content).select('a>span.designer')
    table_url=[(i.text).upper() for i in lst]
    table_brand+=table_url
table_brand

['OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 'LES RÊVERIES',
 'CECILIE BAHNSEN',
 'JACQUEMUS',
 'ALTUZARRA',
 'LA COLLECTION',
 'PREEN BY THORNTON BREGAZZI',
 'GANNI',
 'MONSE',
 'PETER PILOTTO',
 'GANNI',
 'PUSHBUTTON',
 'HAIDER ACKERMANN',
 'VETEMENTS',
 'RICK OWENS',
 'JIL SANDER',
 'PACO RABANNE',
 'CHLOÉ',
 'ISABEL MARANT',
 'ALTUZARRA',
 'COMMISSION',
 'OSCAR DE LA RENTA',
 'STELLA MCCARTNEY',
 'BERNADETTE',
 'STELLA MCCARTNEY',
 'ALEXANDER MCQUEEN',
 'BURBERRY',
 'ALAÏA',
 'ASAI',
 'AKRIS',
 'ANDERSSON BELL',
 'LELA ROSE',
 'DE LA VALI',
 'PROENZA SCHOULER',
 'PUSHBUTTON',
 'GIAMBATTISTA VALLI',
 'HOLZWEILER',
 'MONSE',
 'JACQUEMUS',
 'PRADA',
 'REJINA PYO',
 'LES RÊVERIES',
 'STELLA MCCARTNEY',
 'VALENTINO',
 'DEVEAUX',
 'GANNI',
 'PRADA',
 'PUSHBUTTON',
 'A.W.A.K.E. MODE',
 'A.W.A.K.E. MODE',
 'ALEXANDER MCQUEEN',
 'DEITAS',
 'PROENZA SCHOULER',
 'ASAI',
 'BOTTEGA VENETA',
 'VICTORIA BECKHAM',
 'ROLAND MOURET',
 'ALEKSANDRE AKHALKATSISHVILI',
 'CHLOÉ',
 'VERSACE',
 'GIVENCHY',
 ...]

In [4]:
table_price=[]
for i in range(1,68):
    if i%2==0:
            t.sleep(3)
    url='https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Dresses?cm_sp=topnav-_-clothing-_-dresses&pn=%i&npp=60&image_view=product&dscroll=0'
    lst=BS(r.get(url=url,headers=headers).content).select('span.price')
    table_url=[(i.text).strip('\n\t€').replace(',','') for i in lst]
    table_price=table_price+table_url
table_price

['3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 '699',
 '1970',
 '1039',
 '1275',
 '890',
 '1062',
 '200',
 '1971',
 '1145',
 '330',
 '833',
 '1530',
 '1350',
 '970',
 '1290',
 '850',
 '990',
 '2700',
 '1495',
 '1369',
 '3495',
 '1195',
 '605',
 '1095',
 '2890',
 '2290',
 '3630',
 '1727',
 '2190',
 '472',
 '1494',
 '611',
 '1578',
 '756',
 '4455',
 '190',
 '2073',
 '492',
 '3900',
 '900',
 '755',
 '1295',
 '3980',
 '863',
 '420',
 '2950',
 '600',
 '858',
 '858',
 '11990',
 '1055',
 '1090',
 '795',
 '1900',
 '1950',
 '1115',
 '523',
 '4790',
 '1680',
 '1990',
 ...]

In [5]:
table_desc=[]
for i in range(1,68):
    if i%2==0:
            t.sleep(3)
    url='https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Dresses?cm_sp=topnav-_-clothing-_-dresses&pn='+str(i)+'&npp=60&image_view=product&dscroll=0'
    lst=BS(r.get(url,headers=headers).content).select('div.description>a')
    table_url=[''.join(re.findall(r'title=.*',str(j))).strip('">\"[]').replace('&amp;','&').replace('title=','').replace('"','').replace(' - NET SUSTAIN','') for j in lst]
    table_desc+=table_url     
table_desc

['Robe midi en crêpe de laine mélangée à imprimé fleuri et à plis surpiqués',
 'Robe en crêpe à finitions en cuir synthétique',
 'Robe longue en jersey stretch à imprimé fleuri Jil',
 'Robe midi en toile de coton à ceinture',
 'Robe midi bicolore en mailles côtelées',
 'Robe en cady à finitions en cuir et à ceinture ',
 'Robe longue en laine floquée à pois',
 'Robe longue en serge à carreaux et à volants Country Poet',
 'Robe midi en laine à plis',
 'Robe midi en crêpe à imprimé fleuri, à plis et à col noué',
 'Robe en mailles jacquard',
 'Robe midi en satin à imprimé fleuri Clara',
 'Robe midi en mousseline de soie mélangée imprimée et en dentelle à clous',
 'Robe midi en crêpe de laine à drapé et à sac ceinture',
 'Robe midi en organza à sequins, à broderies et à volants',
 'Robe longue en mailles côtelées Norritt ',
 'Robe asymétrique en laine mérinos à découpe',
 'Robe longue en mailles côtelées La Robe Maille Azur',
 'Robe du soir en satinette de coton à imprimé fleuri et à appliqué',
 'Robe midi en satin, laine et laine mélangée Tanika',
 'Robe midi en crêpe de Chine de soie à imprimé fleuri et à finitions en dentelle',
 'Robe en jacquard de soie à finitions en cuir synthétique',
 'Robe du soir asymétrique effet cape en cady de soie',
 'Robe-chemise en Tencel Nye',
 'Robe midi en satin de soie stretch imprimé ',
 'Robe midi épaules nues en tweed de laine mélangée à ornements et à fronces',
 'Robe midi effet cape en crêpe de Chine à pois et à plis',
 'Robe midi en mailles côtelées Renton ',
 'Robe midi en mailles côtelées Renton',
 'Robe midi en mailles stretch à ornements',
 'Robe longue oversize en cloqué à liens sur le devant Artemis ',
 'Robe midi asymétrique en crêpe imprimé',
 'Robe en laine et en voile de coton imprimée Ashley',
 'Robe en mailles stretch à découpe',
 'Robe midi en crêpe imprimé',
 'Robe en crêpe évasée Liman',
 'Robe midi en serge à fronces et à chaînes',
 'Robe du soir en georgette de soie à imprimé fleuri, à broderies et à nœud lavallière',
 'Robe midi en satin de soie à ornements et à drapés',
 'Robe midi en soie mélangée côtelée',
 'Robe midi en crêpe de Chine de soie à imprimé serpent',
 'Robe midi en organza et en fil coupé Ammi',
 'Robe en crêpe de Chine à ceinture Seya',
 'Robe midi plissée en mousseline à imprimé cachemire Lakshmi ',
 'Robe effet portefeuille en satin de soie à ceinture Eleni',
 'Robe midi en mousseline dévorée à imprimé fleuri Lydia ',
 'Robe midi en georgette à imprimé fleuri, plis souples et volants',
 'Robe asymétrique en coton brossé à carreaux et à fronces',
 'Robe midi en coton à imprimé fleuri',
 'Robe midi en popeline à fronces et à cristaux',
 'Robe midi en taffetas de soie à fronces et à volants ',
 'Robe midi en jersey de laine, en satin et en jacquard ',
 'Robe dos ouvert en crêpe stretch à imprimé fleuri et à drapés',
 'Robe portefeuille en crêpe drapée',
 'Robe midi en cachemire, laine et soie mélangés chinés',
 'Robe en charmeuse à cristaux',
 'Mini-robe en laine mérinos mélangée à motif jacquard et à boutons',
 'Robe midi asymétrique effet portefeuille en cuir Fanelia',
 'Mini-robe en jersey de laine, crêpe de soie mélangée et brocart à imprimé cachemire Belinda',
 'Robe midi en satin à chaînes',
 'Robe midi oversize en tulle à sequins Amira',
 'Robe midi à col montant en laine et en nylon',
 'Robe portefeuille en georgette à imprimé tigre',
 'Robe en crêpe à finitions en cuir et en daim synthétiques ',
 'Robe midi asymétrique en popeline de coton imprimée à ceinture',
 'Robe midi en satin de soie à pois et à fronces Talulah',
 'Robe midi en laine mélangée côtelée',
 'Robe midi asymétrique en mousseline et en fil coupé à imprimé fleuri Julinea ',
 'Robe longue en velours stretch tie & dye',
 'Robe midi en velours imprimé',
 'Robe asymétrique en jacquard de soie mélangée métallisée à col noué Melodi',
 'Robe longue asymétrique en mousseline de soie à imprimé serpent et à superpositions ',
 'Robe midi en coton à carreaux et à fronces',
 'Robe portefeuille froncée en lamé stretch',
 'Robe midi en organza',
 'Robe midi en satin',
 'Robe midi asymétrique en crêpe et en jersey de coton à drapé',
 'Cardigan portefeuille en laine',
 'Robe longue en jersey Soirée',
 'Cardigan en laine à ceinture',
 'Robe midi en velours et en satin ',
 'Robe en laine à ceinture',
 'Robe en mailles côtelées bicolores à drapés',
 'Mini-robe en velours de coton imprimé à fronces et à boutons',
 'Robe portefeuille en mailles à broderies',
 'Robe midi plissée en jersey satiné à fronces',
 'Robe midi à col montant en laine à rayures',
 'Robe portefeuille en satin de soie stretch bicolore à ceinture',
 'Robe midi en jersey stretch à imprimé fleuri et à volants Alta',
 'Robe longue en satin de soie à imprimé fleuri et à ornements',
 'Robe en velours à imprimé fleuri et à fronces',
 'Robe midi en jersey de coton rayé',
 'Robe en velours stretch à découpe et à boucle',
 'Robe asymétrique en serge de soie à pois et à ceinture Dublin',
 'Robe longue oversize en crêpe satiné à plis surpiqués et à volants Cara',
 'Robe longue en organza de soie Virginia',
 'Robe longue en serge de soie nouée sur le devant Artemis',
 'Robe midi en mousseline de soie imprimée à drapés',
 'Robe longue en Lurex à volants Audrey',
 'Robe en georgette de soie imprimée Pompe',
 'Robe en serge de soie à imprimé Fillmore',
 'Robe en serge de soie imprimée',
 'Robe en georgette de soie imprimée Cadell ',
 'Robe midi en mailles stretch côtelées à rayures Sunday',
 'Robe midi en mailles stretch côtelées à rayures Sunday',
 'Robe midi en mailles stretch côtelées à rayures Sunday',
 'Robe midi en crêpe Ardmore',
 'Mini-robe en satin martelé imprimé nouée au cou',
 'Robe en crêpe évasée Liman',
 'Robe asymétrique en crêpe Darley',
 'Robe épaules nues en crêpe à drapés Arch',
 'Robe midi en serge de laine brossée à ceinture',
 'Robe du soir en dentelle guipure à broderies',
 'Robe midi en crêpe Etty',
 'Robe en crêpe à drapés Augustus',
 'Mini-robe asymétrique en mailles stretch à volants Mikey',
 'Robe midi effet cape en crêpe imprimé',
 'Robe midi en crêpe',
 'Mini-robe en crêpe de laine à imprimé léopard',
 'Robe midi en crêpe à imprimé fleuri et à sequins',
 'Robe épaules nues en mailles pointelle Stansfield',
 'Robe midi en laine côtelée à rayures',
 'Robe midi en tulle brodé à finitions en velours et à appliqués',
 'Robe en jersey stretch à imprimé fleuri Reese',
 'Robe midi en dentelle guipure et en tulle brodée',
 'Robe midi en crêpe à nœuds Lavete',
 'Robe en crêpe de laine à fronces Colimbo',
 'Robe midi en crêpe de Chine de soie à imprimé fleuri Sylvia',
 'Robe midi en mousseline de soie à ceinture Delfi',
 'Robe du soir en tulle à finitions en velours et à superpositions',
 'Robe en jersey stretch à imprimé fleuri Dylanne',
 'Mini-robe oversize en laine mélangée',
 'Robe midi en cady bicolore à volants Rhonda',
 'Mini-robe en jersey stretch à drapé et à fronces',
 'Robe en satin de soie plissée bicolore Ada',
 'Mini-robe en mailles stretch',
 'Robe midi en poil de chameau et soie mélangés',
 'Robe midi asymétrique patchwork en serge de laine et de soie mélangées à nœud lavallière',
 'Robe portefeuille en mousseline de soie à imprimé fleuri et à volants',
 'Robe du soir en velours dévoré Josephine',
 'Robe effet portefeuille en crêpe de Chine imprimé',
 'Mini-robe en mailles jacquard stretch à boutons ',
 'Robe midi en lin à imprimé fleuri Zinnia',
 'Mini-robe en crêpe imprimé Seville',
 'Mini-robe en broderie anglaise de lin et coton mélangés à ceinture Edie ',
 'Caftan en voile à imprimé fleuri Samoa',
 'Mini-robe en lin imprimée à volants Edie ',
 'Robe longue effet portefeuille en mousseline imprimée à fronces Elke',
 'Mini-robe dos nu en voile de coton et lin mélangés à pois Zinnia ',
 'Robe midi en crépon de coton et soie mélangés à imprimé fleuri et à smocks Zinnia',
 'Robe en jersey de coton Milo',
 'Robe midi en voile de coton à broderies Zinnia',
 'Robe de plage en dentelle de coton mélangé Mel ',
 'Robe midi en voile de coton imprimé à ceinture Edie ',
 'Robe du soir asymétrique en crêpe stretch à ornements',
 'Robe midi dos ouvert en soie à imprimé fleuri Zinnia ',
 'Robe midi en lin à houppes et à ceinture Edie ',
 'Robe du soir épaules nues en tulle à fronces et à paillettes',
 'Robe en mailles texturées',
 'Robe midi en velours stretch à fronces',
 'Robe midi en crêpe à sequins Williams ',
 'Robe longue en gaze de ramie à imprimé fleuri à fronces et à volants Zinnia',
 'Robe en voile à imprimé fleuri et à découpe Teresa ',
 'Robe porte-feuille en crêpe à imprimé fleuri Sammy',
 'Cafetan en cloqué de soie effet croco',
 'Cafetan en cloqué de soie effet croco',
 'Robe midi dos ouvert en jersey de Tencel stretch Jameson',
 'Mini-robe dos ouvert en crêpe Kira',
 'Robe asymétrique en crêpe Jolie',
 'Mini-robe bustier en crêpe à drapés Turner',
 'Mini-robe en crêpe satiné à drapés Roberts',
 'Mini-robe dos ouvert en cady à cristaux Inka',
 'Mini-robe en satin de soie à fronces',
 'Robe longue en mousseline à pois Stacey',
 'Robe du soir bustier en crêpe à sequins Howard ',
 'Robe longue en coton et soie mélangés à imprimé fleuri Huayna',
 'Mini-robe bustier en voile et en crochet Joy',
 'Robe en mailles point de Rome stretch à imprimé fleuri Martine',
 'Cafetan en mousseline de soie mélangée et en fil coupé',
 'Robe longue en voile à imprimé tigre',
 'Robe midi en mailles point de Rome stretch et en satin à imprimé fleuri et à ceinture Hilma',
 'Robe longue en voile de coton à imprimé fleuri Cora',
 'Mini-robe en cotte de mailles Cara ',
 'Robe en cady et en dentelle de Chantilly à nœud',
 'Robe midi en laine mélangée bicolore Tilda',
 'Robe longue en mousseline à pois Harriet',
 'Robe midi en satin de soie Keats',
 'Mini-robe en broderie anglaise de coton à volants Kara',
 'Mini-robe asymétrique en laine mélangée Tia',
 'Mini-robe asymétrique en velours Ambre ',
 'Mini-robe effet portefeuille en Lurex ombré ',
 'Robe effet portefeuille en laine mélangée Blake',
 'Robe longue en mousseline à imprimé fleuri Maria',
 'Cafetan en dentelle stretch crochetée à liens Nina',
 'Robe midi en crêpe à sequins et à franges Matisse',
 'Robe en crêpe à volants et à ceinture Romea',
 'Robe midi en georgette imprimée Orchard',
 'Robe midi en mousseline de soie imprimée Mavis',
 'Robe midi en résille stretch imprimée',
 'Robe longue en taffetas ',
 'Robe midi bustier en jersey stretch froncé Slinky',
 'Pull en cachemire',
 'Robe portefeuille en voile imprimé Brianna',
 'Mini-robe en jacquard de soie à imprimé fleuri, à finitions métallisées et à volants',
 'Robe asymétrique en jean à volants',
 'Cafetan asymétrique en voile imprimé Pamela',
 'Robe midi à col montant en cady et en serge à smocks',
 'Robe midi torsadée sur le devant en serge à ceinture',
 'Mini-robe en coton et soie mélangés à imprimé fleuri et à smocks Huayna ',
 'Cafetan en Lurex de soie mélangée à rayures',
 'Cafetan oversize en crêpe de Chine de soie imprimé',
 'Robe longue asymétrique en jersey stretch à drapé Honey',
 'Robe en popeline de coton mélangé à imprimé fleuri et à finitions en gros-grain',
 'Robe longue épaules nues en jersey stretch',
 'Robe longue à encolure américaine en soie Super Eight',
 'Mini-robe en cuir synthétique à ornements ',
 'Robe en tulle à drapés',
 'Robe du soir dos ouvert en cloqué Winslow',
 'Robe midi en coton imprimé à volants Olivia',
 'Robe longue dos ouvert en satin Esme',
 'Robe longue torsadée sur le devant en Lurex ombré à découpe',
 'Robe midi en coton imprimé à volants Olivia',
 'Robe du soir nouée sur le devant en voile métallisé à finitions en tulle',
 'Robe midi dos nu convertible en jersey stretch Caro ',
 'Robe portefeuille en cupro',
 'Robe en macramé à sequins Noix',
 'Mini-robe en cuir synthétique effet serpent Antonia x Pernille Teisbaek',
 'Mini-robe asymétrique en cuir synthétique métallisé craquelé Kayla x Pernille Teisbaek',
 'Robe midi dos nu convertible en jersey stretch Caro ',
 'Mini-robe effet portefeuille en satin à drapé',
 'Mini-robe effet portefeuille en jacquard léopard métallisé Vienna',
 'Robe midi en satin martelé à fronces',
 'Robe longue asymétrique en mousseline de soie mélangée et fil coupé métallisé Solana ',
 'Robe midi en gaze de lin mélangé métallisée à franges Ojai',
 'Mini-robe asymétrique en cuir Kayla x Pernille Teisbaek',
 'Mini-robe en satin de soie à fronces',
 'Mini-robe en organza métallisé à fronces',
 'Mini-robe portefeuille en mousseline et en velours à sequins Julie',
 'Robe en crêpe de Chine imprimée Colca ',
 'Robe midi en satin et en dentelle à fronces et à superposition',
 'Mini-robe asymétrique en mailles côtelées ',
 'Robe portefeuille asymétrique en mousseline dévorée Katherine ',
 'Robe midi en gaze de lin mélangé métallisée à ceinture Poet',
 'Robe longue portefeuille en crêpe à imprimé zèbre',
 'Robe midi portefeuille en crêpe à imprimé fleuri Fran',
 'Robe midi en crêpe bicolore à volants Ronda',
 'Robe midi en crêpe à imprimé fleuri et à volants Jean-Marie',
 'Robe midi en popeline de coton à imprimé fleuri Josianne',
 'Robe midi en tulle à sequins Liza',
 'Mini-robe en crêpe à imprimé fleuri à smocks Margherita ',
 'Mini-robe en laine à sequins et à fronces',
 'Mini-robe en crêpe à imprimé fleuri et à smocks Donna',
 'Robe midi portefeuille en soie à volants Super Eight ',
 'Robe longue en gaze à drapé Neeta',
 'Mini-robe en crêpe à imprimé fleuri et à volants Serafina ',
 'Mini-robe en fil coupé et en georgette à houppes et à plis',
 'Robe longue en mousseline à sequins, à finitions en velours et à rayures Rebecca ',
 'Mini-robe portefeuille en soie Super Eight',
 'Mini-robe asymétrique en serge de coton mélangé Paula ',
 'Robe midi en gaze de lin mélangé Alison',
 'Robe longue en crêpe imprimé à liens à nouer Hotel Beau',
 'Mini-robe en mousseline de soie mélangée à imprimé léopard et en fil coupé Marisa',
 'Mini-robe plissée en laine grain de poudre mélangée à imprimé fleuri',
 'Robe midi en crêpe de Chine de soie imprimée à volants Ginny',
 'Robe oversize plissée en lin flammé Mega',
 'Robe midi en mailles côtelées à rayures',
 'Mini-robe en voile à plis nervures et à finitions en crochet',
 'Robe midi en crêpe de Chine de soie à pois et à volants Super Eight',
 'Robe midi en crêpe de Chine à imprimé fleuri Samoa',
 'Robe longue torsadée sur le devant en Lurex ombré à découpe',
 'Robe asymétrique en georgette à sequins et à ceinture ',
 'Mini-robe en mousseline, fil coupé et georgette imprimées',
 'Robe midi en crêpe de Chine de soie Super Eight',
 'Robe midi en crêpe de Chine à imprimé léopard Elsa ',
 'Robe longue en georgette de soie à imprimé fleuri et à chaînes Samoa',
 'Robe midi en Lurex plissé à fronces',
 'Mini-robe en serge de coton à superpositions drapées en crêpe de Chine',
 'Robe en tulle à ornements et à volants Eden',
 'Robe longue en voile à imprimé zèbre et à smocks',
 'Robe midi plissée en crêpe satiné',
 'Mini-robe dos ouvert en mousseline à sequins et à finitions en velours Tender Fury',
 'Mini-robe en crêpe de Chine de soie à imprimé léopard Kyla',
 'Robe midi en mailles côtelées métallisées à découpes',
 'Robe midi en mousseline à pois',
 'Robe midi en voile à finitions en gros-grain Tyler',
 'Robe en cuir vegan à ceinture Rosana',
 'Robe midi en crêpe de Chine de soie et en georgette à imprimé fleuri Denise ',
 'Robe longue en Tencel à fronces ',
 'Robe longue en voile de coton à rayures Liliane',
 'Robe midi en laine mélangée à ornements ',
 'Robe en voile à ceinture Ada',
 'Robe midi en Tencel stretch',
 'Robe épaules nues en mailles torsadées de laine mélangée',
 'Robe en Tencel stretch',
 'Mini-robe en soie à imprimé fleuri Fara',
 'Robe longue patchwork en mailles crochetées de coton métallisées',
 'Robe midi en lin à ceinture Super Eight ',
 'Robe longue en lin à smocks',
 'Robe en georgette de soie à imprimé fleuri et à volants Tammy',
 'Robe midi épaules nues en coton et soie mélangés à imprimé fleuri Lily',
 'Mini-robe dos ouvert en cotte de mailles Hailey',
 'Robe longue en mailles côtelées Noritt ',
 'Robe en crêpe de Chine à carreaux Giselle',
 'Robe midi en georgette imprimée et en fil coupé à ceinture',
 'Robe longue épaules nues en mousseline à imprimé fleuri et à smocks Monique',
 'Robe du soir en jersey stretch à fronces',
 'Robe en mousseline à imprimé fleuri et à smocks Evelyn',
 'Robe midi en crêpe à carreaux et à volants Noemie ',
 'Robe longue en crêpe de soie à pois',
 'Robe en serge de soie imprimée Apollo',
 'Mini-robe en dentelle crochetée',
 'Robe midi épaules nues en lin vichy à smocks Atlanta',
 'Mini-robe effet portefeuille en jersey stretch à finitions en satin Remi',
 'Robe en piqué à rayures',
 'Robe portefeuille en mousseline à pois et à volants ',
 'Robe midi en cuir synthétique à fronces',
 'Robe midi en crépon à imprimé fleuri Farah ',
 'Mini-robe en crêpe à imprimé fleuri Jeanette',
 'Mini-robe en satin lavé à lacets Pantha ',
 'Mini-robe en crêpe à imprimé fleuri et à volants Lou Lou ',
 'Robe midi épaules nues en lin à pois et à smocks Atlanta ',
 'Mini-robe en crêpe à imprimé fleuri Rafhaela',
 'Combi-pantalon dos ouvert à effet robe en jersey stretch à imprimé fleuri',
 'Robe midi en crêpe de Chine imprimée Shaanti ',
 'Mini-robe en lin à smocks et à volants Cette',
 'Robe midi en satin martelé à ceinture et à découpes Porter',
 'Cafetan en voile de coton mélangé à rayures et à franges métallisées Zinab',
 'Robe midi portefeuille en satin Grace',
 'Mini-robe en crêpe à imprimé fleuri Ilia',
 'Robe en mailles stretch à plis plats',
 'Robe midi en jacquard léopard métallisé à ceinture Vienna',
 'Robe longue en crépon de coton The Sienna',
 'Robe midi portefeuille en crêpe à imprimé fleuri Marta ',
 'Robe midi en jersey stretch imprimé ',
 'Robe midi épaules nues en lin à volants',
 'Robe midi portefeuille en crépon de coton et soie mélangés à imprimé fleuri Misty ',
 'Mini-robe effet portefeuille en voile à carreaux et à volants',
 'Cafetan en crêpe de Chine de soie imprimé à ornements',
 'Robe du soir asymétrique en tulle à sequins',
 'Robe longue en mousseline plissée imprimée Aria',
 'Mini-robe en lin et soie mélangés à imprimé fleuri Morgan ',
 'Robe en mousseline à ornements et à découpes ',
 'Robe midi en crêpe à imprimé fleuri Emilia ',
 'Robe longue en voile imprimé à volants Colca',
 'Robe asymétrique en jersey stretch à imprimé léopard et à fronces Diana ',
 'Robe en satin à imprimé fleuri et à ceinture Baily',
 'Robe longue en crêpe imprimé Alhena',
 'Robe midi en voile à imprimé fleuri Delia',
 'Robe en jersey stretch imprimé à finitions en dentelle',
 'Robe longue en mousseline à sequins Camille ',
 'Mini-robe en lin imprimé à ceinture Brigitte ',
 'Robe portefeuille en jersey à imprimé fleuri Fabrizia',
 'Mini-robe en cuir vegan effet serpent à ceinture Lorena',
 'Robe midi en lamé à drapé',
 'Robe en soie imprimée Noe',
 'Robe midi en satin de soie Stella',
 'Mini-robe en crêpe à imprimé zèbre Ilia ',
 'Robe longue à capuche en jersey stretch à drapé Neeta ',
 'Robe en georgette plissée à chaîne Hayden',
 'Robe midi épaules nues en serge de coton à drapés',
 'Mini-robe en jersey de coton à broderies',
 'Robe longue en gaze de coton biologique froissée à ceinture Luna',
 'Mini-robe en coton mélangé et dentelle crochetée Vaiana',
 'Mini-robe en coton mélangé et en dentelle crochetée Marilyn ',
 'Robe midi épaules nues en lin à fronces Atlanta ',
 'Robe longue en fil coupé à ceinture',
 'Robe longue en jersey de coton',
 'Robe du soir effet portefeuille en tulle à sequins et à découpes',
 'Robe portefeuille en jacquard de soie à rayures',
 'Mini-robe en jersey ornée de paillettes',
 'Mini-robe en crêpe à imprimé serpent métallisé et à fronces Diaz',
 'Robe épaules nues en voile de coton imprimé à smocks',
 'Mini-robe en Lurex à cristaux',
 'Robe portefeuille en mousseline à imprimé fleuri et à volants Ysabelle',
 'Robe midi en crêpe à sequins et à franges Matisse',
 'Robe midi en crêpe de Chine imprimé à volants Melissandre',

In [6]:
colnames=['Brand', 'Description','OriginalPrice']

In [7]:
df_dress=pd.DataFrame([table_brand,table_desc,table_price], index=colnames).T
df_dress

,Brand,Description,OriginalPrice
0,OSCAR DE LA RENTA,Robe midi en crêpe de laine mélangée à imprimé...,3495
1,STELLA MCCARTNEY,Robe en crêpe à finitions en cuir synthétique,1195
2,BERNADETTE,Robe longue en jersey stretch à imprimé fleuri...,605
3,STELLA MCCARTNEY,Robe midi en toile de coton à ceinture,1095
4,ALEXANDER MCQUEEN,Robe midi bicolore en mailles côtelées,2890
5,BURBERRY,Robe en cady à finitions en cuir et à ceinture,2290
6,ALAÏA,Robe longue en laine floquée à pois,3630
7,ASAI,Robe longue en serge à carreaux et à volants C...,1727
8,AKRIS,Robe midi en laine à plis,2190
9,ANDERSSON BELL,"Robe midi en crêpe à imprimé fleuri, à plis et...",472
10,LELA ROSE,Robe en mailles jacquard,1494
11,DE LA VALI,Robe midi en satin à imprimé fleuri Clara,611
12,PROENZA SCHOULER,Robe midi en mousseline de soie mélangée impri...,1578
13,PUSHBUTTON,Robe midi en crêpe de laine à drapé et à sac c...,756
14,GIAMBATTISTA VALLI,"Robe midi en organza à sequins, à broderies et...",4455
15,HOLZWEILER,Robe longue en mailles côtelées Norritt,190
16,MONSE,Robe asymétrique en laine mérinos à découpe,2073
17,JACQUEMUS,Robe longue en mailles côtelées La Robe Maille...,492
18,PRADA,Robe du soir en satinette de coton à imprimé f...,3900
19,REJINA PYO,"Robe midi en satin, laine et laine mélangée Ta...",900
20,LES RÊVERIES,Robe midi en crêpe de Chine de soie à imprimé ...,755
21,STELLA MCCARTNEY,Robe en jacquard de soie à finitions en cuir s...,1295
22,VALENTINO,Robe du soir asymétrique effet cape en cady de...,3980
23,DEVEAUX,Robe-chemise en Tencel Nye,863
24,GANNI,Robe midi en satin de soie stretch imprimé,420
25,PRADA,Robe midi épaules nues en tweed de laine mélan...,2950
26,PUSHBUTTON,Robe midi effet cape en crêpe de Chine à pois ...,600
27,A.W.A.K.E. MODE,Robe midi en mailles côtelées Renton,858
28,A.W.A.K.E. MODE,Robe midi en mailles côtelées Renton,858
29,ALEXANDER MCQUEEN,Robe midi en mailles stretch à ornements,11990
...,...,...,...
3990,DEITAS,None,1055
3991,PROENZA SCHOULER,None,1090
3992,ASAI,None,795
3993,BOTTEGA VENETA,None,1900
3994,VICTORIA BECKHAM,None,1950
3995,ROLAND MOURET,None,1115
3996,ALEKSANDRE AKHALKATSISHVILI,None,523
3997,CHLOÉ,None,4790
3998,VERSACE,None,1680
3999,GIVENCHY,None,1990
4000,LES RÊVERIES,None,699
4001,CECILIE BAHNSEN,None,1970
4002,JACQUEMUS,None,1039
4003,ALTUZARRA,None,1275
4004,LA COLLECTION,None,890
4005,PREEN BY THORNTON BREGAZZI,None,1062
4006,GANNI,None,200
4007,MONSE,None,1971
4008,PETER PILOTTO,None,1145
4009,GANNI,None,330
4010,PUSHBUTTON,None,833
4011,HAIDER ACKERMANN,None,1530
4012,VETEMENTS,None,1350
4013,RICK OWENS,None,970
4014,JIL SANDER,None,1290
4015,PACO RABANNE,None,850
4016,CHLOÉ,None,990
4017,ISABEL MARANT,None,2700
4018,ALTUZARRA,None,1495
4019,COMMISSION,None,1369

In [8]:
df_dress.duplicated().sum()

11

In [9]:
df_dress=df_dress.drop_duplicates()

In [10]:
df_dress.Description='Dress'
df_dress

C:\Users\mathi\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

                            Brand Description OriginalPrice
0               OSCAR DE LA RENTA       Dress          3495
1                STELLA MCCARTNEY       Dress          1195
2                      BERNADETTE       Dress           605
3                STELLA MCCARTNEY       Dress          1095
4               ALEXANDER MCQUEEN       Dress          2890
5                        BURBERRY       Dress          2290
6                           ALAÏA       Dress          3630
7                            ASAI       Dress          1727
8                           AKRIS       Dress          2190
9                  ANDERSSON BELL       Dress           472
10                      LELA ROSE       Dress          1494
11                     DE LA VALI       Dress           611
12               PROENZA SCHOULER       Dress          1578
13                     PUSHBUTTON       Dress           756
14             GIAMBATTISTA VALLI       Dress          4455
15                     HOLZWEILER       Dress           190
16                          MONSE       Dress          2073
17                      JACQUEMUS       Dress           492
18                          PRADA       Dress          3900
19                     REJINA PYO       Dress           900
20                   LES RÊVERIES       Dress           755
21               STELLA MCCARTNEY       Dress          1295
22                      VALENTINO       Dress          3980
23                        DEVEAUX       Dress           863
24                          GANNI       Dress           420
25                          PRADA       Dress          2950
26                     PUSHBUTTON       Dress           600
27                A.W.A.K.E. MODE       Dress           858
28                A.W.A.K.E. MODE       Dress           858
29              ALEXANDER MCQUEEN       Dress         11990
...                           ...         ...           ...
3990                       DEITAS       Dress          1055
3991             PROENZA SCHOULER       Dress          1090
3992                         ASAI       Dress           795
3993               BOTTEGA VENETA       Dress          1900
3994             VICTORIA BECKHAM       Dress          1950
3995                ROLAND MOURET       Dress          1115
3996  ALEKSANDRE AKHALKATSISHVILI       Dress           523
3997                        CHLOÉ       Dress          4790
3998                      VERSACE       Dress          1680
3999                     GIVENCHY       Dress          1990
4000                 LES RÊVERIES       Dress           699
4001              CECILIE BAHNSEN       Dress          1970
4002                    JACQUEMUS       Dress          1039
4003                    ALTUZARRA       Dress          1275
4004                LA COLLECTION       Dress           890
4005   PREEN BY THORNTON BREGAZZI       Dress          1062
4006                        GANNI       Dress           200
4007                        MONSE       Dress          1971
4008                PETER PILOTTO       Dress          1145
4009                        GANNI       Dress           330
4010                   PUSHBUTTON       Dress           833
4011             HAIDER ACKERMANN       Dress          1530
4012                    VETEMENTS       Dress          1350
4013                   RICK OWENS       Dress           970
4014                   JIL SANDER       Dress          1290
4015                 PACO RABANNE       Dress           850
4016                        CHLOÉ       Dress           990
4017                ISABEL MARANT       Dress          2700
4018                    ALTUZARRA       Dress          1495
4019                   COMMISSION       Dress          1369

[4009 rows x 3 columns]

In [11]:
def table_generator(url_pattern,headers,pages_to_scrape):
    table_brand=[]
    table_price=[]
    table_desc=[]
    for i in range(1,pages_to_scrape+1):
        if i%2==0:
            t.sleep(2)
        url=url_pattern%i
        soup=BS(r.get(url,headers=headers).content)
        lst1=soup.select('a>span.designer')
        table_url1=[(j.text).upper() for j in lst1]
        table_brand+=table_url1
        lst2=soup.select('span.price')
        table_url2=[(k.text).strip('\n\t€').replace(',','') for k in lst2]
        table_price+=table_url2
        lst3=soup.select('div.description>a')
        table_url3=[''.join(re.findall(r'title=.*',str(l))).strip('">\"[]').replace('&amp;','&').replace('title=','').replace('"','').replace(' - NET SUSTAIN','') for l in lst3]
        table_desc+=table_url3
        
        
    return table_brand, table_desc, table_price

In [12]:
Brand1,Description1,OriginalPrice1=table_generator(f'https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Pants?cm_sp=topnav-_-clothing-_-pants&pn=%i&npp=60&image_view=product&dScroll=0',headers,25)
df_pants=pd.DataFrame([Brand1,Description1,OriginalPrice1], index=colnames).T
df_pants=df_pants.drop_duplicates()
df_pants.Description='Pants'
df_pants

                               Brand Description OriginalPrice
0                      ROLAND MOURET       Pants           530
1                       MARA HOFFMAN       Pants           350
2                      LA COLLECTION       Pants           485
3                       ENVELOPE1976       Pants           300
4                   STELLA MCCARTNEY       Pants           535
5                        LOW CLASSIC       Pants           250
6                    GABRIELA HEARST       Pants          1280
7                    MOTHER OF PEARL       Pants           335
8                           CASASOLA       Pants           645
9                    MES DEMOISELLES       Pants           355
10                             VINCE       Pants           315
11                        STINE GOYA       Pants           160
12                        RICK OWENS       Pants           535
13                 VIVIENNE WESTWOOD       Pants           635
14                 ALEXANDER MCQUEEN       Pants           940
15                               RTA       Pants           386
16                        JIL SANDER       Pants           890
17                    ALEXANDER WANG       Pants           720
18                  MARQUES' ALMEIDA       Pants           670
19                           VERSACE       Pants           890
20                         DEREK LAM       Pants           550
21                       LOW CLASSIC       Pants           135
22                         JACQUEMUS       Pants           506
23                        JIL SANDER       Pants          1150
24                      ACNE STUDIOS       Pants          1800
25                   GABRIELA HEARST       Pants           650
26                           VERSACE       Pants           850
27                       FORTE_FORTE       Pants           350
28                          CASASOLA       Pants           645
29                          LE KASHA       Pants           550
...                              ...         ...           ...
1413                      BALENCIAGA       Pants           650
1414                      PAUL & JOE       Pants           315
1415                     16ARLINGTON       Pants           435
1416                     SIES MARJAN       Pants           855
1417                 MAISON MARGIELA       Pants           590
1418  PHILOSOPHY DI LORENZO SERAFINI       Pants           215
1419                      BALENCIAGA       Pants           695
1421                TEMPERLEY LONDON       Pants           994
1422                           ALAÏA       Pants          1200
1423                           ALAÏA       Pants          1510
1424                      NILI LOTAN       Pants           375
1425                    RIME ARODAKY       Pants           367
1426                         MIU MIU       Pants           490
1427                           PRADA       Pants           650
1428                 BRANDON MAXWELL       Pants           773
1429                        HELLESSY       Pants           940
1430                           GUCCI       Pants          1200
1431                           GUCCI       Pants           980
1432                           GUCCI       Pants           980
1433                 GABRIELA HEARST       Pants           795
1434                HAIDER ACKERMANN       Pants           555
1435                  ROSIE ASSOULIN       Pants          1107
1436                  VERONICA BEARD       Pants           375
1437                           FIGUE       Pants           466
1438                 MARY KATRANTZOU       Pants           888
1439                     MDS STRIPES       Pants           421
1440              ANN DEMEULEMEESTER       Pants           505
1441                         BASSIKE       Pants           645
1442                            TIBI       Pants           330
1443                            TIBI       Pants          1000

[1388 rows x 3 columns]

In [41]:
Brand2,Description2,OriginalPrice2=table_generator(f'https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Jackets?cm_sp=topnav-_-clothing-_-jackets&pn=%i&npp=60&image_view=product&dScroll=0',headers,19)
df_jacket=pd.DataFrame([Brand2,Description2,OriginalPrice2], index=colnames).T
df_jacket=df_jacket.drop_duplicates()
df_jacket.Description='Jacket'
df_jacket

                            Brand Description OriginalPrice
0                      BALENCIAGA      Jacket          2990
1                         BALMAIN      Jacket          2990
2                   SAINT LAURENT      Jacket          2990
3                         THE ROW      Jacket          4900
4                        GIVENCHY      Jacket          4390
5                           GUCCI      Jacket           690
6                           CHLOÉ      Jacket          3990
7                   ROLAND MOURET      Jacket          1165
8                          MUGLER      Jacket          1704
9                           GUCCI      Jacket          2980
10                        MISSONI      Jacket          1190
11                          GUCCI      Jacket          4980
12                     LORO PIANA      Jacket          4755
13                        BALMAIN      Jacket          1490
14                           ROKH      Jacket          1000
15                       PETER DO      Jacket          1812
16               STELLA MCCARTNEY      Jacket          1095
17                      OFF-WHITE      Jacket          1700
18                    JW ANDERSON      Jacket           977
19                UNRAVEL PROJECT      Jacket           988
20               KWAIDAN EDITIONS      Jacket          1490
21                   FRANKIE SHOP      Jacket           301
22                 ALICE + OLIVIA      Jacket           535
23                       BURBERRY      Jacket           690
24    ALEKSANDRE AKHALKATSISHVILI      Jacket           608
25                          CHLOÉ      Jacket           850
26    ALEKSANDRE AKHALKATSISHVILI      Jacket           608
27    ALEKSANDRE AKHALKATSISHVILI      Jacket           630
28                3.1 PHILLIP LIM      Jacket           788
29                       MAX MARA      Jacket          1075
...                           ...         ...           ...
1076                SAINT LAURENT      Jacket          2241
1077                SAINT LAURENT      Jacket          3591
1078               BOTTEGA VENETA      Jacket          2400
1079             CHRISTOPHER KANE      Jacket          1495
1080              DOLCE & GABBANA      Jacket          1750
1081          MM6 MAISON MARGIELA      Jacket           650
1082                SAINT LAURENT      Jacket          3490
1083                      SAFIYAA      Jacket           935
1084                        GUCCI      Jacket          2890
1085                      BARBOUR      Jacket           124
1086                        PRADA      Jacket          1500
1087                   BALENCIAGA      Jacket          3450
1089                   NILI LOTAN      Jacket          1100
1090                        GUCCI      Jacket          3200
1091                        PRADA      Jacket          1200
1092                        GUCCI      Jacket         10800
1094                        PRADA      Jacket          1550
1095                      MIU MIU      Jacket          1650
1096                        PRADA      Jacket          1990
1097                      MIU MIU      Jacket          1950
1098                      MIU MIU      Jacket          1290
1099                      MIU MIU      Jacket          2800
1100            ALEXANDER MCQUEEN      Jacket          1695
1101              GABRIELA HEARST      Jacket          1795
1102                        GUCCI      Jacket          5121
1103                        PRADA      Jacket          1300
1104                        PRADA      Jacket          4900
1105                        GUCCI      Jacket          1980
1106                   BALENCIAGA      Jacket          3190
1107               ALEXANDER WANG      Jacket          1395

[1077 rows x 3 columns]

In [14]:
Brand3,Description3,OriginalPrice3=table_generator(f'https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Tops?cm_sp=topnav-_-clothing-_-tops&pn=%i&npp=60&image_view=product&dScroll=0',headers,47)
df_top=pd.DataFrame([Brand3,Description3,OriginalPrice3], index=colnames).T
df_top=df_top.drop_duplicates()
df_top.Description='Top'
df_top

                          Brand Description OriginalPrice
0                      NANUSHKA         Top           390
1                 SAINT LAURENT         Top          2490
2              STELLA MCCARTNEY         Top           695
3                          RIXO         Top           215
4                         FENDI         Top           550
5                         GANNI         Top           350
6                      WE11DONE         Top           520
7                    NILI LOTAN         Top           555
8                         GANNI         Top           420
9                       CUSHNIE         Top           856
10                        GUCCI         Top          1100
11              DOLCE & GABBANA         Top           695
12                       HARMUR         Top           318
13                         ROKH         Top           511
14    REMAIN BIRGER CHRISTENSEN         Top           280
15                ROLAND MOURET         Top           735
16                         GMBH         Top           495
17              A.W.A.K.E. MODE         Top           761
18                      BALMAIN         Top           495
19                    JACQUEMUS         Top          1120
20             MARQUES' ALMEIDA         Top           255
21             KWAIDAN EDITIONS         Top           750
22                   BALENCIAGA         Top          1090
23                    OFF-WHITE         Top           920
24                   DE LA VALI         Top           320
25            OSCAR DE LA RENTA         Top          1975
26                       KHAITE         Top          1110
27             VICTORIA BECKHAM         Top           750
28              DRIES VAN NOTEN         Top          1055
29                        LOEWE         Top          1400
...                         ...         ...           ...
2752                      PRADA         Top           790
2753                      PRADA         Top           550
2754              SAINT LAURENT         Top          1690
2755                      ALAÏA         Top           750
2756                      PRADA         Top           980
2757                      GUCCI         Top          1980
2758                    MIU MIU         Top           590
2759                      ALAÏA         Top           780
2760               RIME ARODAKY         Top          1461
2761                      PRADA         Top           790
2762                      PRADA         Top           690
2763                      GUCCI         Top          2200
2764                      PRADA         Top           790
2765               RIME ARODAKY         Top           700
2766                      GUCCI         Top          1100
2767                      PRADA         Top          1290
2768                      PRADA         Top           450
2769                      PRADA         Top           750
2771                      PRADA         Top          1100
2772                 MAISONCLÉO         Top           160
2773                 MAISONCLÉO         Top           160
2774                   GIVENCHY         Top           350
2775               ORSEUND IRIS         Top           607
2776                      FRAME         Top           125
2777              RICHARD QUINN         Top           556
2778                  REEM ACRA         Top          1340
2779      MCQ ALEXANDER MCQUEEN         Top           310
2780                        IRO         Top           340
2781                   MOSCHINO         Top           310
2782                M.I.H JEANS         Top           335

[2604 rows x 3 columns]

In [15]:
Brand4,Description4,OriginalPrice4=table_generator(f'https://www.net-a-porter.com/fr/fr/d/Shop/Clothing/Skirts?cm_sp=topnav-_-clothing-_-skirts&pn=%i&npp=60&image_view=product&dScroll=0',headers,17)
df_skirts=pd.DataFrame([Brand4,Description4,OriginalPrice4], index=colnames).T
df_skirts=df_skirts.drop_duplicates()
df_skirts.Description='Skirt'
df_skirts

                    Brand Description OriginalPrice
0                PETER DO       Skirt          1051
1                    TIBI       Skirt          1225
2        PROENZA SCHOULER       Skirt          1380
3        PROENZA SCHOULER       Skirt          1845
4              BALENCIAGA       Skirt           895
5              NILI LOTAN       Skirt          1505
6           ISABEL MARANT       Skirt          1950
7        PROENZA SCHOULER       Skirt          1015
8              REJINA PYO       Skirt           540
9         A.W.A.K.E. MODE       Skirt           625
10                  LOEWE       Skirt          1100
11       PROENZA SCHOULER       Skirt          1430
12                  MARNI       Skirt          1290
13                  LOEWE       Skirt          2800
14                 JOSEPH       Skirt           345
15    SALVATORE FERRAGAMO       Skirt          2500
16           ACNE STUDIOS       Skirt           520
17                 JOSEPH       Skirt           820
18            JW ANDERSON       Skirt           784
19                  GANNI       Skirt           450
20       CHRISTOPHER KANE       Skirt           895
21             REJINA PYO       Skirt           595
22                 JOSEPH       Skirt           595
23              JACQUEMUS       Skirt           642
24      ALEXANDER MCQUEEN       Skirt          4990
25        GABRIELA HEARST       Skirt          3000
26          PETER PILOTTO       Skirt           865
27         ANDERSSON BELL       Skirt           324
28           ACNE STUDIOS       Skirt           480
29               PETER DO       Skirt          1051
...                   ...         ...           ...
975                 PRADA       Skirt           890
976            BALENCIAGA       Skirt          1290
977               THE ROW       Skirt          1580
978        BOTTEGA VENETA       Skirt          2800
979            BALENCIAGA       Skirt           695
981                 PRADA       Skirt          1650
982                 ALAÏA       Skirt          1140
983                 PRADA       Skirt           720
984      CHRISTOPHER KANE       Skirt           895
985      HALFPENNY LONDON       Skirt          1722
986                 GUCCI       Skirt          1500
987                 ALAÏA       Skirt          3250
988                 ALAÏA       Skirt          2080
989                 GUCCI       Skirt          4980
990                 PRADA       Skirt          1650
991                 GUCCI       Skirt          2600
992                 PRADA       Skirt           550
993                 PRADA       Skirt           750
994                 GUCCI       Skirt          2037
995            SID NEIGUM       Skirt           230
996                 PRADA       Skirt          2100
997                 PRADA       Skirt          2550
998         VANESSA BRUNO       Skirt           250
999         ISABEL MARANT       Skirt          1750
1000              MIU MIU       Skirt          1100
1001                ADEAM       Skirt           540
1002            ALTUZARRA       Skirt          1325
1003                 ETRO       Skirt          1040
1004        SAINT LAURENT       Skirt          1590
1005                 TIBI       Skirt           445

[986 rows x 3 columns]


# .
# Group By Brand

In [16]:
def mode_agg(x):
    return(''.join(x.mode().values.tolist()))

In [17]:
df_skirts.OriginalPrice=df_skirts.OriginalPrice.astype('int')
df_skirts1=df_skirts.groupby('Brand').agg({'Description':mode_agg,'OriginalPrice':'mean'}).reset_index().copy()
df_skirts1

                           Brand Description  OriginalPrice
0                    16ARLINGTON       Skirt     873.750000
1                3.1 PHILLIP LIM       Skirt     552.875000
2                A.W.A.K.E. MODE       Skirt     584.000000
3                   ACNE STUDIOS       Skirt     390.000000
4                    ADAM LIPPES       Skirt    1842.500000
5                          ADEAM       Skirt     540.000000
6              AGENT PROVOCATEUR       Skirt     278.000000
7                         AGNONA       Skirt     935.000000
8                         AGOLDE       Skirt     169.000000
9           AGUA BY AGUA BENDITA       Skirt     500.000000
10                         AKRIS       Skirt    1206.666667
11                         ALAÏA       Skirt    2550.909091
12                   ALBUS LUMEN       Skirt     340.000000
13   ALEKSANDRE AKHALKATSISHVILI       Skirt     364.000000
14               ALESSANDRA RICH       Skirt     600.000000
15                     ALEX MILL       Skirt     104.000000
16                    ALEXACHUNG       Skirt     235.000000
17             ALEXANDER MCQUEEN       Skirt    1617.142857
18                ALEXANDER WANG       Skirt     826.428571
19               ALEXANDERWANG.T       Skirt     285.000000
20            ALEXANDRE VAUTHIER       Skirt    1527.500000
21                ALICE + OLIVIA       Skirt     514.166667
22                        ALLUDE       Skirt     459.000000
23                     ALTUZARRA       Skirt     958.333333
24                         AMIRI       Skirt    1954.000000
25                ANDERSSON BELL       Skirt     382.666667
26                    ANINE BING       Skirt     259.857143
27            ANN DEMEULEMEESTER       Skirt    1108.000000
28                    ANNA MASON       Skirt     603.666667
29                     ANNA QUAN       Skirt     390.000000
..                           ...         ...            ...
236                       SPRWMN       Skirt     785.000000
237                 STAND STUDIO       Skirt     397.000000
238                        STAUD       Skirt     200.000000
239             STELLA MCCARTNEY       Skirt     960.000000
240                   STINE GOYA       Skirt     313.500000
241             TEMPERLEY LONDON       Skirt     869.666667
242                THE LINE BY K       Skirt     181.250000
243           THE MIGHTY COMPANY       Skirt     653.000000
244                      THE ROW       Skirt    1778.500000
245                       THEORY       Skirt     470.000000
246                  THOM BROWNE       Skirt    1260.000000
247                         TIBI       Skirt     561.111111
248                     TOM FORD       Skirt    1120.000000
249                   TORY BURCH       Skirt     437.333333
250                       TOTÊME       Skirt     240.000000
251                 ULLA JOHNSON       Skirt     604.714286
252              UNRAVEL PROJECT       Skirt    1471.000000
253                    VALENTINO       Skirt    2044.285714
254                VANESSA BRUNO       Skirt     267.857143
255               VERONICA BEARD       Skirt     452.500000
256                      VERSACE       Skirt    1148.181818
257                    VETEMENTS       Skirt    1070.000000
258             VICTORIA BECKHAM       Skirt     896.000000
259   VICTORIA, VICTORIA BECKHAM       Skirt     435.500000
260                        VINCE       Skirt     391.111111
261            VIVIENNE WESTWOOD       Skirt     460.000000
262                 WALES BONNER       Skirt     560.000000
263                 WE ARE LEONE       Skirt     506.000000
264                     WE11DONE       Skirt     470.000000
265                   ZIMMERMANN       Skirt    1029.000000

[266 rows x 3 columns]

In [18]:
df_dress.OriginalPrice=df_dress.OriginalPrice.astype('int')
df_dress1=df_dress.groupby('Brand').agg({'Description':mode_agg,'OriginalPrice':'mean'}).reset_index().copy()
df_dress1

                          Brand Description  OriginalPrice
0               A.W.A.K.E. MODE       Dress     858.000000
1                         AKRIS       Dress    2190.000000
2                         ALAÏA       Dress    3630.000000
3   ALEKSANDRE AKHALKATSISHVILI       Dress     523.000000
4             ALEXANDER MCQUEEN       Dress    7440.000000
5                     ALTUZARRA       Dress    1385.827068
6                ANDERSSON BELL       Dress     472.000000
7                          ASAI       Dress    1261.000000
8                    BERNADETTE       Dress     605.000000
9                BOTTEGA VENETA       Dress    1900.000000
10                     BURBERRY       Dress    2290.000000
11              CECILIE BAHNSEN       Dress    1970.000000
12                        CHLOÉ       Dress    2890.000000
13                   COMMISSION       Dress    1369.000000
14                   DE LA VALI       Dress     611.000000
15                       DEITAS       Dress    1055.000000
16                      DEVEAUX       Dress     863.000000
17                        GANNI       Dress     316.150000
18           GIAMBATTISTA VALLI       Dress    4455.000000
19                     GIVENCHY       Dress    1990.000000
20             HAIDER ACKERMANN       Dress    1530.000000
21                   HOLZWEILER       Dress     190.000000
22                ISABEL MARANT       Dress    2700.000000
23                    JACQUEMUS       Dress     765.500000
24                   JIL SANDER       Dress    1290.000000
25                LA COLLECTION       Dress     890.000000
26                    LELA ROSE       Dress    1494.000000
27                 LES RÊVERIES       Dress     727.000000
28                        MONSE       Dress    2022.000000
29            OSCAR DE LA RENTA       Dress    3495.000000
30                 PACO RABANNE       Dress     850.000000
31                PETER PILOTTO       Dress    1145.000000
32                        PRADA       Dress    3428.571429
33   PREEN BY THORNTON BREGAZZI       Dress    1062.000000
34             PROENZA SCHOULER       Dress    1334.000000
35                   PUSHBUTTON       Dress     729.666667
36                   REJINA PYO       Dress     900.000000
37                   RICK OWENS       Dress     970.000000
38                ROLAND MOURET       Dress    1115.000000
39             STELLA MCCARTNEY       Dress    1195.000000
40                    VALENTINO       Dress    3980.000000
41                      VERSACE       Dress    1680.000000
42                    VETEMENTS       Dress    1350.000000
43             VICTORIA BECKHAM       Dress    1950.000000

In [19]:
df_pants.OriginalPrice=df_pants.OriginalPrice.astype('int')
df_pants1=df_pants.groupby('Brand').agg({'OriginalPrice':'mean','Description':mode_agg}).reset_index().copy()
df_pants1

                                  Brand  OriginalPrice Description
0                           16ARLINGTON     725.714286       Pants
1                       3.1 PHILLIP LIM     564.250000       Pants
2                       A.W.A.K.E. MODE     499.000000       Pants
3                          ACNE STUDIOS     765.555556       Pants
4                           ADAM LIPPES     780.000000       Pants
5                     ADAM SELMAN SPORT     211.500000       Pants
6    ADIDAS ORIGINALS BY ALEXANDER WANG     195.000000       Pants
7                                AGNONA    1064.000000       Pants
8                                AGOLDE     216.500000       Pants
9                                 AKRIS    1049.500000       Pants
10                                ALAÏA    1212.000000       Pants
11                          ALBUS LUMEN     295.000000       Pants
12          ALEKSANDRE AKHALKATSISHVILI     250.000000       Pants
13                            ALEX MILL     143.666667       Pants
14                           ALEXACHUNG     385.000000       Pants
15                    ALEXANDER MCQUEEN     979.285714       Pants
16                       ALEXANDER WANG     720.000000       Pants
17                      ALEXANDERWANG.T     315.000000       Pants
18                   ALEXANDRE VAUTHIER     785.000000       Pants
19                       ALICE + OLIVIA     449.000000       Pants
20                         ALICE MCCALL     345.000000       Pants
21                               ALLUDE     337.666667       Pants
22                            ALTUZARRA     767.307692       Pants
23                              AMBUSH®     616.500000       Pants
24                       ANDERSSON BELL     336.750000       Pants
25                            ANDREW GN     960.000000       Pants
26                           ANINE BING     210.000000       Pants
27                   ANN DEMEULEMEESTER     819.666667       Pants
28                           ANNA MASON     629.666667       Pants
29                            ANNA QUAN     507.500000       Pants
..                                  ...            ...         ...
267                 THE ELDER STATESMAN     953.000000       Pants
268                           THE GREAT     222.000000       Pants
269                       THE LINE BY K     252.750000       Pants
270                           THE RANGE     309.750000       Pants
271                             THE ROW    1225.357143       Pants
272                              THEORY     401.904762       Pants
273                         THOM BROWNE    1323.333333       Pants
274                                TIBI     609.000000       Pants
275                            TOM FORD    1540.000000       Pants
276                          TORY BURCH     346.500000       Pants
277                              TOTÊME     320.000000       Pants
278             TRE BY NATALIE RATABESI    1320.500000       Pants
279                     TWENTY MONTRÉAL     219.600000       Pants
280                        ULLA JOHNSON     485.000000       Pants
281                     UNRAVEL PROJECT    1092.800000       Pants
282                           VALENTINO    1135.000000       Pants
283                       VANESSA BRUNO     278.333333       Pants
284                      VERONICA BEARD     409.166667       Pants
285                             VERSACE     712.000000       Pants
286                           VETEMENTS     705.000000       Pants
287                    VICTORIA BECKHAM     857.142857       Pants
288          VICTORIA, VICTORIA BECKHAM     383.857143       Pants
289                               VINCE     388.000000       Pants
290                   VIVIENNE WESTWOOD     528.333333       Pants
291                        WALES BONNER     805.000000       Pants
292                        WE ARE LEONE     521.000000       Pants
293                            WE11DONE     436.666667       Pants
294                             WOLFORD     144.000000       Pants
295                 WRIGHT LE CHAPELAIN     684.500000       Pants
296                          ZIMMERMANN     457.500000       Pants

[297 rows x 3 columns]

In [20]:
df_top.OriginalPrice=df_top.OriginalPrice.astype('int')
df_top1=df_top.groupby('Brand').agg({'OriginalPrice':'mean','Description':mode_agg}).reset_index().copy()
df_top1

                                  Brand  OriginalPrice Description
0                           16ARLINGTON     686.555556         Top
1                       3.1 PHILLIP LIM     503.083333         Top
2                       A.W.A.K.E. MODE     517.666667         Top
3                          ACNE STUDIOS     242.941176         Top
4                           ADAM LIPPES     732.777778         Top
5                     ADAM SELMAN SPORT     156.000000         Top
6                      ADIDAS ORIGINALS      41.666667         Top
7    ADIDAS ORIGINALS BY ALEXANDER WANG     180.000000         Top
8                     AGENT PROVOCATEUR     256.000000         Top
9                                AGNONA     630.000000         Top
10                               AGOLDE     118.428571         Top
11                 AGUA BY AGUA BENDITA     239.000000         Top
12                                AKRIS     864.333333         Top
13                                ALAÏA    1259.642857         Top
14                          ALBUS LUMEN     287.500000         Top
15          ALEKSANDRE AKHALKATSISHVILI     295.000000         Top
16                            ALEX MILL     102.833333         Top
17                           ALEX PERRY    1100.000000         Top
18                           ALEXACHUNG     141.250000         Top
19                    ALEXANDER MCQUEEN    1180.769231         Top
20                       ALEXANDER WANG     603.125000         Top
21                      ALEXANDERWANG.T     328.928571         Top
22                   ALEXANDRE VAUTHIER    1090.000000         Top
23                       ALICE + OLIVIA     313.571429         Top
24                         ALICE MCCALL     245.000000         Top
25                             ALIX NYC     188.423077         Top
26                            ALTUZARRA     775.000000         Top
27                              AMBUSH®     318.200000         Top
28                                AMIRI     556.666667         Top
29                       ANDERSSON BELL     221.000000         Top
..                                  ...            ...         ...
316                 THE ELDER STATESMAN     678.750000         Top
317                           THE GREAT     205.750000         Top
318                       THE LINE BY K     115.666667         Top
319                           THE RANGE     197.523810         Top
320                             THE ROW    1074.807692         Top
321                              THEORY     314.130435         Top
322                         THOM BROWNE     680.000000         Top
323                                TIBI     382.000000         Top
324                            TOM FORD    1130.000000         Top
325                          TORY BURCH     378.333333         Top
326                              TOTÊME     400.000000         Top
327             TRE BY NATALIE RATABESI     721.000000         Top
328                     TWENTY MONTRÉAL     158.727273         Top
329                        ULLA JOHNSON     424.450000         Top
330                     UNRAVEL PROJECT     522.600000         Top
331                           VALENTINO    1232.272727         Top
332                       VANESSA BRUNO     273.750000         Top
333                      VERONICA BEARD     340.000000         Top
334                             VERSACE     649.461538         Top
335                           VETEMENTS     470.454545         Top
336                    VICTORIA BECKHAM     769.166667         Top
337          VICTORIA, VICTORIA BECKHAM     302.571429         Top
338                               VINCE     234.375000         Top
339                   VIVIENNE WESTWOOD     545.000000         Top
340                        WALES BONNER     576.666667         Top
341                            WE11DONE     560.416667         Top
342                             WOLFORD     165.846154         Top
343                 WRIGHT LE CHAPELAIN     687.500000         Top
344                      YEAH RIGHT NYC     113.875000         Top
345                          ZIMMERMANN     564.500000         Top

[346 rows x 3 columns]

In [42]:
df_jacket.OriginalPrice=df_jacket.OriginalPrice.astype('int')
df_jacket1=df_jacket.groupby('Brand').agg({'OriginalPrice':'mean','Description':mode_agg}).reset_index().copy()
df_jacket1

                           Brand  OriginalPrice Description
0                    16ARLINGTON     765.000000      Jacket
1                3.1 PHILLIP LIM     759.750000      Jacket
2                   ACNE STUDIOS    1476.428571      Jacket
3              ADAM SELMAN SPORT     375.000000      Jacket
4               ADIDAS ORIGINALS      70.000000      Jacket
5                         AGNONA    4360.000000      Jacket
6                          AKRIS    2790.000000      Jacket
7                          ALAÏA    3635.714286      Jacket
8    ALEKSANDRE AKHALKATSISHVILI     615.333333      Jacket
9                ALESSANDRA RICH    1615.000000      Jacket
10                    ALEXACHUNG     426.666667      Jacket
11             ALEXANDER MCQUEEN    2877.368421      Jacket
12                ALEXANDER WANG    1716.250000      Jacket
13            ALEXANDRE VAUTHIER    2135.000000      Jacket
14                ALICE + OLIVIA     574.285714      Jacket
15                     ALTUZARRA    1518.000000      Jacket
16                       AMBUSH®     946.666667      Jacket
17                         AMIRI    1465.000000      Jacket
18                ANDERSSON BELL     799.000000      Jacket
19                     ANDREW GN    2100.000000      Jacket
20                    ANINE BING     375.000000      Jacket
21            ANN DEMEULEMEESTER    1309.800000      Jacket
22                    ANNA MASON     764.000000      Jacket
23                     ANNA QUAN     675.000000      Jacket
24                          AREA    1238.000000      Jacket
25                         ARIAS    1085.000000      Jacket
26                         ARIES    2129.000000      Jacket
27                          ARJÉ    1002.500000      Jacket
28                        ASCENO     670.000000      Jacket
29             ATLANTIQUE ASCOLI     740.000000      Jacket
..                           ...            ...         ...
219             TEMPERLEY LONDON     782.666667      Jacket
220                       TEMPLA    2634.000000      Jacket
221                THE LINE BY K     293.000000      Jacket
222           THE MIGHTY COMPANY    1203.555556      Jacket
223                      THE ROW    2871.470588      Jacket
224                       THEORY     565.000000      Jacket
225                  THOM BROWNE    1955.000000      Jacket
226                         TIBI     837.000000      Jacket
227                     TOM FORD    3000.000000      Jacket
228                       TOTÊME     796.000000      Jacket
229      TRE BY NATALIE RATABESI     863.000000      Jacket
230              TWENTY MONTRÉAL     267.000000      Jacket
231                 ULLA JOHNSON     685.000000      Jacket
232              UNRAVEL PROJECT     988.000000      Jacket
233                        UTZON    2508.000000      Jacket
234                    VALENTINO    3153.333333      Jacket
235                VANESSA BRUNO     795.000000      Jacket
236               VERONICA BEARD     752.857143      Jacket
237                      VERSACE    2602.857143      Jacket
238                    VETEMENTS    1277.500000      Jacket
239             VICTORIA BECKHAM    1700.000000      Jacket
240   VICTORIA, VICTORIA BECKHAM     447.500000      Jacket
241                        VINCE     520.000000      Jacket
242            VIVIENNE WESTWOOD    1012.500000      Jacket
243                 WALES BONNER    1795.000000      Jacket
244                 WE ARE LEONE     506.000000      Jacket
245                     WE11DONE     824.375000      Jacket
246          WRIGHT LE CHAPELAIN    1079.000000      Jacket
247                 YVES SALOMON    2600.000000      Jacket
248                   ZIMMERMANN    1700.000000      Jacket

[249 rows x 3 columns]


# .
# Create SQL engine

In [46]:
import pymysql
from sqlalchemy import create_engine

In [47]:
engine=create_engine(f'mysql+pymysql://root:2547TZcm2437@localhost/netaporter')


# .
# Import Data Frames to SQL

In [48]:
df_dress1.to_sql('DressNAP',engine,if_exists='replace',index=False)

C:\Users\mathi\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\x92\\xE9t\\xE9)' for column 'VARIABLE_VALUE' at row 1")
  result = self._query(query)

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost/netaporter): (DressNAP)

In [49]:
df_pants1.to_sql('PantsNAP',engine,if_exists='replace',index=False)

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost/netaporter): (PantsNAP)

In [50]:
df_jacket1.to_sql('JacketNAP',engine,if_exists='replace',index=False)

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost/netaporter): (JacketNAP)

In [51]:
df_top1.to_sql('TopNAP',engine,if_exists='replace',index=False)

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost/netaporter): (TopNAP)

In [52]:
df_skirts1.to_sql('SkirtNAP',engine,if_exists='replace',index=False)

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@localhost/netaporter): (SkirtNAP)


# .
# Save to CSV

In [53]:
df_dress1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\DressNAP.csv',index=False)

In [54]:
df_pants1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\PantsNAP.csv',index=False)

In [55]:
df_jacket1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\JacketNAP.csv',index=False)

In [56]:
df_top1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\TopNAP.csv',index=False)

In [57]:
df_skirts1.to_csv(r'C:\Users\mathi\Documents\GitHub\data-labs\module-1\lab-web-scraping\SkirtNAP.csv',index=False)


# .

# Read SQL

In [58]:
Dress=pd.read_sql_query('select * from netaporter.dressnap',engine)

In [59]:
Pants=pd.read_sql_query('select * from netaporter.pantsnap',engine)

In [60]:
Jacket=pd.read_sql_query('select * from netaporter.jacketnap',engine)

In [61]:
Top=pd.read_sql_query('select * from netaporter.topnap',engine)

In [62]:
Skirt=pd.read_sql_query('select * from netaporter.skirtnap',engine)